import {localAPI,assetURL,watchComfy,escapeHTML as esc} from './lib/muapi.js';
import {mountEcosystem,prepare} from './ecosystem.js';
export const bytes=n=>(n/1e9).toFixed(2)+' GB';
const action=(fn)=>async e=>{const button=e.currentTarget;button.disabled=true;try{await fn(e)}catch(err){window.originNotice(err.message,true)}finally{if(button.isConnected)button.disabled=false}};
export function ModelsPage(state){
 const el=document.createElement('section');el.className='origin-page';
 el.innerHTML=`<div class="origin-title"><div><p class="origin-kicker">LOCAL MODEL LIBRARY</p><h1>Model library</h1><p>Starter packs, Hugging Face, Civitai and your Stability Matrix library. Choose a source above.</p></div><input id="catalog-search" aria-label="Search local models" placeholder="Search models, photography, fast…"></div>
 <div class="origin-machine"><strong>${esc(state.hardware.cpu)}</strong><span>${bytes(state.hardware.memory_bytes)} RAM · ${state.hardware.threads} CPU threads · ${esc(state.hardware.gpus)}</span><small>RAM figures below are starting estimates, not benchmark guarantees. Your native engine probes Vulkan / Metal and falls back to CPU. ComfyUI reports the device it actually uses.</small></div>
 <details class="origin-card origin-engine"><summary>ComfyUI · install or connect an engine</summary><div><h2>ComfyUI engine</h2><p>Install the official portable Windows environment, or connect one you already run. Model files are shared across all workflows.</p><p id="comfy-status" role="status">Not connected yet</p></div><div class="origin-actions"><button id="comfy-install">Install portable ComfyUI</button><button id="comfy-start">Start installed engine</button><button id="comfy-test">Test connection</button><button id="comfy-editor">Open full workflow editor ↗</button></div><form id="comfy-connection"><label>Local address<input id="comfy-url" value="${esc(state.config.comfy_url)}" required></label><label>Device<select id="comfy-device"><option value="auto">Auto · detected GPU</option><option value="cpu">CPU compatibility</option><option value="intel">Intel</option><option value="nvidia">NVIDIA</option><option value="amd">AMD</option></select></label><button>Save connection</button></form><details><summary>Existing ComfyUI: model folders</summary><p>Use this directory as the base path in your ComfyUI extra_model_paths.yaml:</p><code>${esc(state.model_folder)}</code><p>Folders: checkpoints, diffusion_models, text_encoders, vae, loras. The managed portable install configures these automatically. Refresh the ComfyUI editor after a download.</p></details></details>
 <div id="model-cards" class="origin-catalog"></div>`;
 const list=el.querySelector('#model-cards');
 const render=filter=>{list.replaceChildren();for(const row of state.catalog){const m=row.model;if(!(m.id+' '+m.name+' '+m.description).toLowerCase().includes(filter.toLowerCase()))continue;const card=document.createElement('article');card.className='origin-card';card.dataset.model=m.id;card.innerHTML=`<div class="origin-card-head"><span class="origin-badge">${m.engine==='native'?'NATIVE':'COMFYUI'}</span><span class="${row.installed?'origin-ready':''}">${row.installed?'Files ready':'Download required'}</span></div><h2>${esc(m.name)}</h2><p>${esc(m.description)}</p><div class="origin-specs"><span>${m.engine==='native'?'6.52 GB':bytes(row.download_bytes)} download</span><span>${m.ram_gb}+ GB RAM estimate</span><span>${m.steps} default steps · ${m.width} px</span></div><p class="origin-license">${esc(m.license)} · <a href="${esc(m.source)}" target="_blank" rel="noopener">Model card & terms ↗</a></p><div class="origin-actions"><button data-install>${row.installed?'Verify files':'Download model pack'}</button><button data-use>${state.config.active_model===m.id?'Selected':'Use model'}</button></div>`;
 card.querySelector('[data-install]').onclick=action(async()=>{await localAPI('/api/studio/install',{id:m.id});window.originNotice('Download started. Progress remains visible above; you can keep using the workspace.')});
 card.querySelector('[data-use]').textContent=m.recipe==='workflow'?'Use in workflows':'Set up & use';card.querySelector('[data-use]').onclick=action(async()=>{if(m.recipe==='workflow'){window.originNavigate('workflows');return}await prepare(m.id)});list.append(card)}};
 render('');el.querySelector('#catalog-search').oninput=e=>render(e.target.value);
 el.querySelector('#comfy-device').value=state.config.device;
 const probe=async()=>{const v=await localAPI('/api/studio/comfy',{});el.querySelector('#comfy-status').textContent='Connected · '+(v.system.devices||[]).map(d=>d.name).join(',')+' · '+v.nodes.length+' node types';return v};
 el.querySelector('#comfy-test').onclick=action(probe);
 el.querySelector('#comfy-install').onclick=action(async()=>{await localAPI('/api/studio/comfy-setup',{});window.originNotice('Official portable download started. No separate Python installation is required.')});
 el.querySelector('#comfy-start').onclick=action(async()=>{await localAPI('/api/studio/comfy-start',{});window.originNotice('Starting ComfyUI. Check Engine status for live readiness and logs.');setTimeout(()=>probe().catch(e=>window.originNotice(e.message,true)),2500)});
 el.querySelector('#comfy-editor').onclick=action(async()=>{const v=await probe();window.open(v.editor_url,'_blank','noopener')});
 el.querySelector('#comfy-connection').onsubmit=action(async e=>{e.preventDefault();await localAPI('/api/studio/config',{...state.config,comfy_url:el.querySelector('#comfy-url').value.replace(/\/$/,''),device:el.querySelector('#comfy-device').value});window.originNotice('Connection saved.');await probe()});
  probe().catch(err=>{el.querySelector('#comfy-status').textContent=err.message});mountEcosystem(el,state);return el;
}
export function BrandingPage(state){
 const el=document.createElement('section');el.className='origin-page';el.innerHTML=`<p class="origin-kicker">YOUR NAME. YOUR WORKSPACE.</p><h1>White-label settings</h1><p>Use your organisation’s name, logo and colour on this local studio. Licence and source notices remain available in About.</p><form id="brand-form" class="origin-card origin-brand-form"><label>Studio name<input id="brand-name" maxlength="60" required value="${esc(state.config.brand)}"></label><label>Tagline<input id="brand-tagline" maxlength="160" value="${esc(state.config.tagline)}"></label><label>Accent colour<input id="brand-accent" type="color" value="${esc(state.config.accent)}"></label><label>Logo image<input id="brand-logo" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="origin-check"><input id="brand-clear-logo" type="checkbox">Remove custom logo</label><button>Save branding</button></form><section class="origin-card"><h2>About & licences</h2><p>This studio adapts the image, camera, reference picker and cinema components of <a href="https://github.com/Autom8AI/Open-Higgsfield-AI" target="_blank" rel="noopener">Autom8AI/Open-Higgsfield-AI</a>, pinned at b5781089. Upstream declares MIT in its README; the original declaration and modification record are included.</p><p>ComfyUI is a separately downloaded GPL-3.0 engine. Its code, model weights and third-party dependencies retain their own licences. White labelling does not remove those obligations or turn hosted commercial models into free weights.</p><a href="/open-studio/README.md" target="_blank">Original upstream README</a> · <a href="https://github.com/HUGELU/HASL" target="_blank" rel="noopener">Complete ORIGIN source</a></section>`;
 el.querySelector('#brand-form').onsubmit=action(async e=>{e.preventDefault();const latest=await localAPI('/api/studio/state',{});let logo=latest.config.logo||'';const file=el.querySelector('#brand-logo').files[0];if(file){if(file.size>4e6)throw new Error('Choose a logo below 4 MB');logo=(await localAPI('/api/upload?name='+encodeURIComponent(file.name),file)).id}if(el.querySelector('#brand-clear-logo').checked)logo='';await localAPI('/api/studio/config',{...latest.config,brand:el.querySelector('#brand-name').value,tagline:el.querySelector('#brand-tagline').value,accent:el.querySelector('#brand-accent').value,logo});window.originNotice('Branding saved.');window.originNavigate('branding')});return el;
}
export function WorkflowsPage(state){
 const el=document.createElement('section');el.className='origin-page';el.innerHTML=`<p class="origin-kicker">COMFYUI · FULL WORKFLOW ACCESS</p><h1>Go beyond a single prompt.</h1><p>Use ComfyUI’s node editor for multi-reference editing, masks, ControlNet, video, audio, 3D and custom nodes. Capabilities depend on the workflow, installed nodes and model weights.</p><div class="origin-actions"><button id="workflow-editor">Open ComfyUI editor ↗</button><a href="https://docs.comfy.org/interface/features/template" target="_blank" rel="noopener">Official workflow templates ↗</a><button id="workflow-finishing">ORIGIN upscaling & production</button></div><form id="workflow-form" class="origin-card"><h2>Run an API workflow inside ORIGIN</h2><p>Export API format from your ComfyUI editor, then import it here. The graph is sent intact to your local engine. ORIGIN saves its outputs and the exact graph.</p><label>API workflow JSON<input id="workflow-file" type="file" accept=".json,application/json"></label><label>Workflow<textarea id="workflow-json" rows="12" required spellcheck="false" placeholder='{"1":{"class_type":"...","inputs":{...}}}'></textarea></label><label>Job label<input id="workflow-label" placeholder="Architectural walkthrough, reference edit, video scene…"></label><button>Validate and queue workflow</button><p id="workflow-result" role="status"></p></form><p>Importing a workflow does not install custom nodes or grant access to paid partner APIs. ComfyUI returns the actual missing-node / model errors. Review a workflow before running it in your environment.</p>`;
 el.querySelector('#workflow-editor').onclick=action(async()=>{const v=await localAPI('/api/studio/comfy',{});window.open(v.editor_url,'_blank','noopener')});
 el.querySelector('#workflow-finishing').onclick=()=>window.parent.originStudioHost?.('production');
 el.querySelector('#workflow-file').onchange=action(async e=>{const f=e.target.files[0];if(f.size>4e6)throw new Error('Workflow exceeds 4 MB');el.querySelector('#workflow-json').value=await f.text()});
 el.querySelector('#workflow-form').onsubmit=action(async e=>{e.preventDefault();let g=JSON.parse(el.querySelector('#workflow-json').value);if(g.prompt)g=g.prompt;const j=await localAPI('/api/studio/workflow',{graph:g,prompt:el.querySelector('#workflow-label').value});watchComfy(j.id);el.querySelector('#workflow-result').textContent='Queued '+j.id+'. Watch Gallery & queue for the actual result.'});return el;
}
export async function GalleryPage(state){
 const native=await localAPI('/api/images/state',{}),jobs=[...(native.jobs||[]),...(state.jobs||[])].sort((a,b)=>b.created-a.created);
 const el=document.createElement('section');el.className='origin-page';el.innerHTML='<p class="origin-kicker">DURABLE OUTPUTS & PARAMETERS</p><div class="origin-title"><h1>Gallery & queue</h1><button id="gallery-refresh">Refresh queue</button></div><div class="origin-catalog" id="studio-gallery"></div>';
 el.querySelector('#gallery-refresh').onclick=()=>window.originNavigate('gallery');
 if(!jobs.length)el.querySelector('#studio-gallery').textContent='Your native and ComfyUI generations will appear here, with their parameters and errors.';
 for(const j of jobs.slice(0,100)){const card=document.createElement('article');card.className='origin-card';card.dataset.job=j.id;card.innerHTML=`<div class="origin-card-head"><strong>${esc(j.status)}</strong><span>${esc(j.request.model||'Z-Image-Turbo')}</span></div><p>${esc(j.request.prompt||'Custom workflow')}</p><p class="origin-job-message">${esc(j.message)}</p><div class="origin-results"></div><div class="origin-actions"><button data-params>Download parameters</button><button data-reuse>Reuse prompt</button></div>`;
 card.querySelector('[data-params]').onclick=action(async()=>{const detail=j.id.startsWith('comfy-')?await localAPI('/api/studio/job',{id:j.id}):j;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(detail,null,2)],{type:'application/json'}));a.download=j.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)});
 card.querySelector('[data-reuse]').onclick=()=>{window.originDraft={...j.request,model:j.request.model||'native-z-image'};window.originNavigate('image')};
 for(const a of (j.assets||[j.asset].filter(Boolean))){const box=document.createElement('div');const mime=a.mime||'image/png';const media=document.createElement(mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':'img');media.alt=j.request.prompt||'Generated output';if(media.tagName!=='IMG')media.controls=true;media.loading='lazy';const observer=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting)){observer.disconnect();assetURL(a.id,mime).then(u=>{media.src=u}).catch(e=>{box.textContent=e.message})}},{rootMargin:'200px'});observer.observe(media);box.append(media);const download=document.createElement('button');download.textContent='Download output';download.onclick=async()=>{const anchor=document.createElement('a');anchor.href=await assetURL(a.id,mime);anchor.download=a.name;anchor.click()};box.append(download);const finish=document.createElement('button');finish.textContent='Upscale / refine';finish.onclick=()=>window.parent.originStudioHost?.('production',a.id);if(mime.startsWith('image/'))box.append(finish);card.querySelector('.origin-results').append(box)}
 if(['queued','running'].includes(j.status)){const stop=document.createElement('button');stop.textContent=j.id.startsWith('img-')?'Cancel job':'Stop / remove queued job';stop.onclick=action(async()=>{await localAPI(j.id.startsWith('img-')?'/api/images/cancel':'/api/studio/cancel',{id:j.id});window.originNavigate('gallery')});card.querySelector('.origin-actions').append(stop)}
 el.querySelector('#studio-gallery').append(card);
 }return el;
}
