'use strict';
const $=id=>document.getElementById(id);
let key=location.hash.slice(1)||sessionStorage.getItem('origin-session')||'';
if(key){sessionStorage.setItem('origin-session',key);history.replaceState(null,'',location.pathname)}
let state=null,page='images',settingsLoaded=false,labBusy=false,labSignature='',blockSignature='',currentUI='',recorder=null,recordStream=null,recordTimer=null,latestAudio='',provider=null,refreshing=false;
const names={activity:'Live work',concepts:'Recurring patterns',hypotheses:'Hypotheses',questions:'Open questions',language:'Binary codebook',swarms:'Internal descendants',interface:'Interface evolution',self:'Source reflection',approvals:'Approvals',experiences:'Experience archive'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString();
const size=n=>{n=Number(n||0);const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<4){n/=1024;i++}return n.toFixed(i?1:0)+' '+units[i]};
const stamp=n=>new Date(n*1000).toLocaleString();
let toastTimer;
function toast(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',6000)}
async function api(path,body,options={}){const headers={'X-Origin-Key':key,...options.headers};const args={method:body===undefined?'GET':'POST',...options,headers};if(body!==undefined){if(body instanceof Blob){args.body=body}else{args.body=JSON.stringify(body);headers['Content-Type']='application/json'}}const r=await fetch(path,args);if(!r.ok)throw new Error((await r.text()).slice(0,800));if(r.status===204||r.status===202)return null;if(options.raw)return r;return r.json()}
function run(fn){return async(...args)=>{try{await fn(...args)}catch(e){toast(e.message,true)}}}
function setPage(next){page=next;for(const el of document.querySelectorAll('.page'))el.hidden=el.id!=='page-'+page;for(const b of document.querySelectorAll('[data-page]'))b.setAttribute('aria-selected',String(b.dataset.page===page));if(state){renderPage();if(page==='settings')loadSettings()}window.scrollTo({top:0,behavior:'instant'})}
for(const b of document.querySelectorAll('[data-page]'))b.addEventListener('click',()=>setPage(b.dataset.page));
function applyLayout(root,g){root.dataset.topology=g.topology||'grid';root.style.setProperty('--cols',Math.min(4,Math.max(1,g.columns||3)));root.style.setProperty('--radius',Math.max(4,g.radius||4)+'px');root.style.setProperty('--density',Math.min(1.15,Math.max(.85,g.density||1)))}
function metric(value,label){return `<div class="metric"><b>${esc(value)}</b><span>${esc(label)}</span></div>`}
function panelContent(id,s){switch(id){
case 'activity':return `<div class="metric-grid">${metric(fmt(s.telemetry.cycles),'work cycles')}${metric(s.telemetry.cycles_per_sec.toFixed(1),'cycles / second')}${metric(s.telemetry.heap_mb.toFixed(1)+' MB','Go heap')}${metric(s.telemetry.active_workers,'configured active workers')}</div><p class="hint">${esc(s.telemetry.backend)} · ${s.telemetry.compute_target}% budget. This is not a CPU-utilisation reading.</p>${(s.events||[]).slice(-6).reverse().map(x=>`<div class="event"><b>${esc(x.kind)}</b>${esc(x.detail)}</div>`).join('')}`;
case 'concepts':return `<div class="metric-grid">${metric(fmt(s.health.total_concepts),'active motifs')}${metric((s.experiences||[]).length,'recent inputs shown')}</div><p class="hint">Recurring 8-byte fragments. These are not established human concepts.</p>${s.concepts.slice(0,12).map(x=>`<div class="item row"><span class="mono">${esc(x.id)}</span><span>${fmt(x.count)} observations</span></div>`).join('')}`;
case 'hypotheses':return `<p class="hint">Repeated inference does not increase observed support. New inputs can add contradictions.</p>${s.hypotheses.slice(0,10).map(x=>`<div class="item"><div class="mono">${esc(x.symbolic)}</div><small>${x.support} support · ${x.contradictions} contradictions · ${fmt(x.inferences)} inferences</small><div class="bar"><i style="width:${Math.round(x.confidence*100)}%"></i></div></div>`).join('')}`;
case 'questions':return `<p class="hint">A useful next input: give a matching example and a counterexample, with the difference explained in your own words.</p>${(s.questions||[]).slice(-5).reverse().map(x=>`<div class="item">${esc(x.human)}</div>`).join('')}`;
case 'language':return `<p class="hint">Frequency-ranked prefix codes for observed motifs. This is a compression convention, not a discovered universal language.</p>${s.language.slice(0,10).map(x=>`<div class="item row"><b class="mono">${esc(x.code||'unassigned')}</b><span class="mono muted">${esc(x.motif)}</span></div>`).join('')}`;
case 'swarms':return `<p class="hint">Descendants keep separate hypothesis memories and exchange actual IDs. Mortality remains a simulated mechanism.</p>${s.swarms.map(x=>`<div class="item"><div class="row spread"><b>${esc(x.id)}</b><small>generation ${x.generation}</small></div><small>${x.local_hypotheses} remembered · ${x.discoveries} first encounters · ${x.exchanges} transfers</small><div><small>${x.alive}/${x.population} simulated population · ${x.extinctions} extinctions</small></div></div>`).join('')}`;
case 'interface':return `<div class="metric-grid">${metric(s.ui_genome.generation,'layout generation')}${metric((s.ui_candidates||[]).length,'candidate layouts')}</div><p>${esc(s.ui_genome.topology)} · ${s.ui_genome.columns} proposed columns</p><p class="hint">${s.lab.auto_ui?'Automatic promotion is enabled when measured requirements pass.':'You apply each layout yourself.'}</p><button data-open="lab">Open interface lab ↗</button>`;
case 'self':return `<p class="hint">${esc(s.lab.engine_note||'Source structure is analysed locally. Code proposals require a configured model or external developer.')}</p>${(s.reflections||[]).slice(-2).reverse().map(x=>`<div class="item">${esc(x.observation)}<p>${esc(x.proposal)}</p></div>`).join('')}<button data-open="archive">Saved states & proposals</button>`;
case 'approvals':return `<p class="hint">These decisions record your intent. An external model connection is configured separately.</p>${(s.approvals||[]).slice(-5).reverse().map(x=>`<div class="item" data-approval="${esc(x.id)}"><b>${esc(x.kind)}</b><p>${esc(x.request)}</p><small>${esc(x.status)}</small>${x.status==='waiting'?`<div class="actions"><button data-approval-id="${esc(x.id)}" data-decision="approve">Approve request</button><button data-approval-id="${esc(x.id)}" data-decision="reject">Reject request</button></div>`:''}</div>`).join('')||'<p>No waiting requests.</p>'}`;
case 'experiences':return `<p class="hint">${size(s.lab.stored_bytes)} / ${size(s.lab.quota_bytes)} of managed raw archive. Files in DROP_HERE remain user-managed.</p>${(s.experiences||[]).slice(-8).reverse().map(x=>`<div class="item"><b>${esc(x.name)}</b><br><small>${size(x.size)} original · ${size(x.sample_bytes)} sampled</small></div>`).join('')}`;
default:return ''}}
function renderLive(){const root=$('live-grid'),g=state.ui_genome,pins=state.lab.pins||[];const order=[...pins,...g.order.filter(id=>!pins.includes(id))];if(currentUI!==g.id||!root.children.length){applyLayout(root,g);for(const id of order){let el=root.querySelector(`[data-panel="${id}"]`);if(!el){el=document.createElement('section');el.className='panel';el.dataset.panel=id;el.innerHTML=`<div class="panel-head"><h2>${names[id]}</h2><div class="controls"><button class="drag-handle" draggable="true" data-drag="${id}" aria-label="Drag ${names[id]}">⠿</button><button data-earlier="${id}" aria-label="Move ${names[id]} earlier">↑</button><button data-pin="${id}" aria-label="Pin ${names[id]}">◇</button></div></div><div class="panel-body"></div>`}root.appendChild(el)}currentUI=g.id}
for(const el of root.children){const id=el.dataset.panel;el.classList.toggle('pinned',pins.includes(id));const pin=el.querySelector('[data-pin]');pin.textContent=pins.includes(id)?'◆':'◇';pin.setAttribute('aria-pressed',String(pins.includes(id)));const body=el.querySelector('.panel-body');if(!body.contains(document.activeElement)){const scroll=body.scrollTop;body.innerHTML=panelContent(id,state);body.scrollTop=scroll}}
const bs=JSON.stringify(state.lab.discovered||[]);if(bs!==blockSignature){const focused=$('blocks').contains(document.activeElement);if(!focused){blockSignature=bs;$('blocks').innerHTML=(state.lab.discovered||[]).map(b=>`<form class="panel" data-block="${esc(b.id)}"><h2>${esc(b.title)}</h2><p>${esc(b.reason)}</p>${b.fields.map(f=>{const id=b.id+'-'+f.id;if(f.kind==='checkbox')return `<label class="check"><input id="${esc(id)}" name="${esc(f.id)}" type="checkbox"> ${esc(f.label)}</label>`;return `<label for="${esc(id)}">${esc(f.label)}${f.required?' *':''}</label>${f.kind==='textarea'?`<textarea id="${esc(id)}" name="${esc(f.id)}" rows="2" ${f.required?'required':''}></textarea>`:`<input id="${esc(id)}" name="${esc(f.id)}" type="${f.kind==='number'?'number':'text'}" ${f.required?'required':''}>`}`}).join('')}<button type="submit" class="primary">Save observation</button></form>`).join('')}}}
function previewHTML(g){const cards=g.order.map(id=>`<section class="panel"><h2>${esc(names[id])}</h2><p>${id==='approvals'?'A capability needs your review.':id==='questions'?'A useful question, an observation, and its supporting evidence.':'Inspect the evidence and compare the next iteration.'}</p><label for="${id}-sample">${id==='experiences'?'Search observations':'Add a note'}</label><input id="${id}-sample" placeholder="Optional note"><button ${id==='approvals'?'data-review="true"':''}>${id==='approvals'?'Review request':'Inspect evidence'}</button></section>`).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${location.origin}/style.css"></head><body class="test-page"><div class="surface-grid" data-topology="${esc(g.topology)}" style="--cols:${Math.min(4,g.columns)};--radius:${Math.max(4,g.radius)}px;--density:${Math.min(1.15,Math.max(.85,g.density))}">${cards}</div></body></html>`}
function newFrame(g,width){const frame=document.createElement('iframe');frame.title='Candidate '+g.id;frame.setAttribute('sandbox','allow-same-origin');if(width)frame.style.width=width+'px';frame.srcdoc=previewHTML(g);return frame}
function showCandidates(){if(labBusy)return;const arr=[state.ui_genome,...(state.ui_candidates||[])];const signature=JSON.stringify([arr.map(x=>[x.id,x.preferred,x.rejected]),state.lab.trials]);if(signature===labSignature)return;labSignature=signature;$('candidates').replaceChildren();for(let i=0;i<arr.length;i++){const g=arr[i],t=state.lab.trials[g.id],el=document.createElement('section');el.className='candidate';el.innerHTML=`<p class="eyebrow">${i===0?'ACTIVE BASELINE':'CANDIDATE '+i}</p><h3>${esc(g.name||g.id)}</h3><small>${esc(g.topology)} · ${g.columns} columns · ${esc(g.rationale||'Current layout')}</small><div class="preview-slot"></div><div class="score">${t?`<span class="${t.pass?'good':'bad'}">${t.pass?'Responsive checks passed':'Layout needs work'}</span><br>${t.samples||0} task trials${t.samples?' · '+(t.total_ms/t.samples/1000).toFixed(2)+'s average · '+t.errors+' errors':''}`:'Awaiting browser measurements'}</div><div class="actions"><button data-test="${esc(g.id)}">Check layout</button><button data-task="${esc(g.id)}" ${!t?.pass?'disabled':''}>Try find-control task</button>${i?`<button data-ui-action="prefer" data-ui-id="${esc(g.id)}">Prefer</button><button data-ui-action="reject" data-ui-id="${esc(g.id)}">Reject</button><button data-ui-action="promote" data-ui-id="${esc(g.id)}" ${!t?.pass?'disabled':''}>Apply</button>`:''}</div>`;el.querySelector('.preview-slot').appendChild(newFrame(g));$('candidates').appendChild(el)}
const usage=Object.values(state.lab.usage||{}).sort((a,b)=>b.count-a.count).slice(0,20);$('usage-view').innerHTML=usage.length?`<div class="table-wrap"><table><thead><tr><th>Interaction</th><th>Target</th><th>Input</th><th>Count</th><th>Total time</th></tr></thead><tbody>${usage.map(u=>`<tr><td>${esc(u.kind)}</td><td>${esc(u.target)}</td><td>${esc(u.device)}</td><td>${fmt(u.count)}</td><td>${(u.total_ms/1000).toFixed(1)}s</td></tr>`).join('')}</tbody></table></div>`:'<p class="hint">Measurements appear as you use the interface. No synthetic measurements are mixed into this table.</p>'}
async function responsiveCheck(g){const checks=[];for(const width of [280,320,390,768,1440,2560]){const f=newFrame(g,width);const ready=new Promise((res,rej)=>{f.onload=res;setTimeout(()=>rej(new Error('Preview took too long to load')),8000)});$('test-host').appendChild(f);await ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const d=f.contentDocument;let small=0,labels=0;const controls=[...d.querySelectorAll('button,input,select,textarea')];for(const el of controls){const rect=el.getBoundingClientRect();if(rect.width<43.9||rect.height<43.9)small++;if(el.tagName==='BUTTON'){if(!el.textContent.trim()&&!el.getAttribute('aria-label'))labels++}else if(!el.labels?.length&&!el.getAttribute('aria-label'))labels++}checks.push({width,overflow:d.documentElement.scrollWidth>width+1,small_targets:small,missing_labels:labels,controls:controls.length});f.remove()};const t=await api('/api/ui/test',{id:g.id,checks,tested:0,pass:false,samples:0,total_ms:0,errors:0,task:''});return t}
async function checkMany(arr){labBusy=true;try{for(let i=0;i<arr.length;i++){$('test-status').textContent=`Testing ${i+1}/${arr.length}: ${arr[i].id}`;await responsiveCheck(arr[i])}$('test-status').textContent='Checks complete. Inspect results below.'}finally{labBusy=false;labSignature='';await refresh()}}
function getUI(id){return [state.ui_genome,...state.ui_candidates].find(x=>x.id===id)}
let trialStarted=0,trialErrors=0,trialID='',trialTimer;
async function startTask(id){if(!state.lab.track)throw new Error('Enable interaction measurement in Settings to record a task trial.');const g=getUI(id);if(!g)return;labBusy=true;trialID=id;trialErrors=0;$('trial-area').hidden=false;$('task-preview').replaceChildren();const f=newFrame(g);f.onload=()=>{trialStarted=performance.now();f.contentDocument.addEventListener('click',run(async e=>{if(!e.target.closest('button'))return;if(e.target.closest('[data-review]')){const ms=performance.now()-trialStarted;await api('/api/ui/task',{id:trialID,ms,errors:trialErrors,task:'find-review'});endTask();toast(`Found in ${(ms/1000).toFixed(2)}s with ${trialErrors} other clicks.`);await refresh()}else{trialErrors++}}));trialTimer=setTimeout(()=>{endTask();toast('Practice ended. No incomplete measurement was recorded.')},120000)};$('task-preview').appendChild(f)}
function endTask(){clearTimeout(trialTimer);labBusy=false;$('trial-area').hidden=true;$('task-preview').replaceChildren();labSignature=''}
function renderArchive(){$('snapshots').innerHTML=(state.lab.snapshots||[]).slice().reverse().map(s=>`<div class="saved"><div><strong>${esc(s.name)}</strong><small>${esc(s.branch)} · ${stamp(s.created)} · ${fmt(s.cycles)} cycles</small><small class="mono">${esc(s.sha256.slice(0,16))}… · verified on restore</small></div><div class="actions">${['restore','branch','merge','join'].map(a=>`<button data-snapshot="${esc(s.id)}" data-snapshot-action="${a}">${({restore:'Restore',branch:'Branch here',merge:'Merge knowledge',join:'Join as descendant'})[a]}</button>`).join('')}</div></div>`).join('')||'<div class="notice">No saved states yet. Save the current iteration above.</div>';$('source-reviews').innerHTML=(state.reflections||[]).slice(-4).reverse().map(x=>`<div class="item">${esc(x.observation)}<p class="hint">${esc(x.proposal)}</p></div>`).join('')}
function refreshAssetSelect(id,predicate){const el=$(id),old=el.value;const items=(state.lab.assets||[]).filter(predicate);const html='<option value="">Select saved material</option>'+items.slice().reverse().map(a=>`<option value="${a.id}">${esc(a.name)} · ${size(a.size)}</option>`).join('');if(el.innerHTML!==html){el.innerHTML=html;el.value=old}}
function renderCreation(){refreshAssetSelect('image-select',x=>x.mime.startsWith('image/'));refreshAssetSelect('audio-select',x=>x.mime.startsWith('audio/'));if(latestAudio)$('audio-select').value=latestAudio;$('transcribe').disabled=!$('audio-select').value;$('asset-list').innerHTML=(state.lab.assets||[]).slice(-18).reverse().map(a=>`<div class="saved"><div><strong>${esc(a.name)}</strong><small>${esc(a.source)} · ${size(a.size)} · ${stamp(a.created)}</small></div><button data-download="${a.id}" data-name="${esc(a.name)}">Download</button></div>`).join('')||'<p class="hint">Your recordings, uploaded files, and generated material appear here.</p>';providerStatus()}
function providerStatus(){$('provider-status').textContent=provider?.enabled?`${provider.base} · ${provider.remaining} requests remaining this session. Model availability is checked when you run a task.`:'No model connected. Local discovery and voice recording are available.'}
function loadSettings(){if(!state)return;$('goal').value=state.lab.goal;$('auto-ui').checked=state.lab.auto_ui;$('track').checked=state.lab.track;$('quota').value=Math.round(state.lab.quota_bytes/(2**30));$('compute').value=String(state.telemetry.compute_target);$('storage-info').textContent=`Archive: ${size(state.lab.stored_bytes)} / ${size(state.lab.quota_bytes)}. ${state.lab.object_count} managed raw objects. Working memory is bounded; multi-terabyte throughput has not been certified. Data folder: ${state.health.state_dir}`;settingsLoaded=true}
function renderPage(){if(!state)return;if(page==='images'&&window.renderNativeImages)window.renderNativeImages();if(page==='learning'&&window.renderEvolution)window.renderEvolution();if(page==='live')renderLive();if(page==='lab')showCandidates();if(page==='archive'&&!$('snapshots').contains(document.activeElement))renderArchive();if(page==='create'&&!$('asset-list').contains(document.activeElement))renderCreation();if(page==='settings'&&!settingsLoaded)loadSettings()}
async function refresh(){if(refreshing)return;refreshing=true;try{state=await api('/api/state');$('engine-status').textContent=state.health.paused?'Paused · inputs remain available':'Local engine running';$('pulse').classList.toggle('off',state.health.paused);$('pause').textContent=state.health.paused?'Resume':'Pause';$('branch-label').textContent=state.lab.branch;$('summary').textContent=`${fmt(state.health.total_concepts)} patterns · ${fmt(state.telemetry.cycles)} cycles`;$('goal-summary').textContent=state.lab.goal;$('approval-count').textContent=state.approvals.filter(x=>x.status==='waiting').length;$('last-save').textContent=state.telemetry.last_checkpoint?'Saved '+new Date(state.telemetry.last_checkpoint*1000).toLocaleTimeString():'Checkpoint pending';renderPage()}catch(e){$('engine-status').textContent='Disconnected';$('pulse').classList.add('off');if(!state)toast(e.message,true)}finally{refreshing=false}}
$('inject').addEventListener('click',run(async()=>{const text=$('observation').value.trim();if(!text)return;await api('/api/observe',{text});$('observation').value='';toast('Observation queued.');await refresh()}));
$('observation').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))$('inject').click()});
async function uploadFiles(files){for(let i=0;i<files.length;i++){const file=files[i];$('input-hint').textContent=`Saving ${i+1}/${files.length}: ${file.name}`;$('upload-progress').hidden=false;const a=await new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/upload?name='+encodeURIComponent(file.name||'voice.webm'));x.setRequestHeader('X-Origin-Key',key);x.setRequestHeader('Content-Type',file.type||'application/octet-stream');x.upload.onprogress=e=>{if(e.lengthComputable)$('upload-progress').value=e.loaded/e.total*100};x.onerror=()=>reject(new Error('Upload interrupted; try the file again.'));x.onload=()=>{if(x.status>=200&&x.status<300){resolve(JSON.parse(x.responseText))}else reject(new Error(x.responseText))};x.send(file)});if(a.mime.startsWith('audio/'))latestAudio=a.id}$('upload-progress').hidden=true;$('input-hint').textContent='Files saved locally. Pattern analysis runs from bounded samples.';await refresh()}
$('fileInput').addEventListener('change',run(async e=>{await uploadFiles([...e.target.files]);e.target.value=''}));
for(const type of ['dragenter','dragover'])document.addEventListener(type,e=>{if([...e.dataTransfer.types].includes('Files')){e.preventDefault();document.body.classList.add('dragover')}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragover')});document.addEventListener('drop',run(async e=>{document.body.classList.remove('dragover');if(e.dataTransfer.files.length){e.preventDefault();await uploadFiles([...e.dataTransfer.files])}}));
$('pause').addEventListener('click',run(async()=>{await api('/api/compute',{paused:!state.health.paused});await refresh()}));
async function saveState(name){await api('/api/snapshot',{name,id:'',action:'save'});toast('Working state saved.');await refresh()}
$('save-top').addEventListener('click',run(()=>saveState('Intermediate success')));$('save-named').addEventListener('click',run(()=>saveState($('snapshot-name').value.trim())));
$('approvals-top').addEventListener('click',()=>{setPage('live');requestAnimationFrame(()=>{const el=document.querySelector('[data-panel="approvals"]');el?.scrollIntoView({block:'center',behavior:'instant'});el?.querySelector('[data-decision]')?.focus()})});
$('connect-shortcut').addEventListener('click',()=>setPage('settings'));
$('new-candidates').addEventListener('click',run(async()=>{await api('/api/ui/new',{});labSignature='';await refresh()}));$('test-all').addEventListener('click',run(()=>checkMany([state.ui_genome,...state.ui_candidates])));$('cancel-trial').addEventListener('click',endTask);
$('blocks').addEventListener('submit',run(async e=>{e.preventDefault();const form=e.target,values={};for(const el of form.elements){if(el.name)values[el.name]=el.type==='checkbox'?String(el.checked):el.value}await api('/api/block',{id:form.dataset.block,values});form.reset();toast('Structured observation saved.');await refresh()}));
let dragged='';$('live-grid').addEventListener('dragstart',e=>{dragged=e.target.dataset.drag||'';if(dragged)e.dataTransfer.setData('text/plain',dragged)});$('live-grid').addEventListener('dragover',e=>{if(dragged)e.preventDefault()});$('live-grid').addEventListener('drop',run(async e=>{if(!dragged)return;e.preventDefault();const target=e.target.closest('[data-panel]')?.dataset.panel;const order=[...state.ui_genome.order];const from=order.indexOf(dragged),to=order.indexOf(target);dragged='';if(from<0||to<0||from===to)return;order.splice(to,0,...order.splice(from,1));await api('/api/ui/reorder',{order});currentUI='';await refresh()}));
document.addEventListener('click',run(async e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.open)setPage(b.dataset.open);
if(b.dataset.pin){const id=b.dataset.pin,pins=[...(state.lab.pins||[])],i=pins.indexOf(id);if(i>=0)pins.splice(i,1);else pins.push(id);await api('/api/settings',{pins});currentUI='';await refresh()}
if(b.dataset.earlier){const order=[...state.ui_genome.order],i=order.indexOf(b.dataset.earlier);if(i>0){[order[i-1],order[i]]=[order[i],order[i-1]];await api('/api/ui/reorder',{order});currentUI='';await refresh()}}
if(b.dataset.test)await checkMany([getUI(b.dataset.test)]);
if(b.dataset.task)await startTask(b.dataset.task);
if(b.dataset.uiAction){await api('/api/ui/action',{id:b.dataset.uiId,action:b.dataset.uiAction});currentUI='';await refresh()}
if(b.dataset.snapshot){await api('/api/snapshot',{id:b.dataset.snapshot,action:b.dataset.snapshotAction,name:$('snapshot-name').value.trim()});toast('Snapshot action completed. Previous state was saved first.');currentUI='';blockSignature='';await refresh()}
if(b.dataset.approvalId){await api('/api/approval/action',{id:b.dataset.approvalId,action:b.dataset.decision});await refresh()}
if(b.dataset.download)await downloadAsset(b.dataset.download,b.dataset.name);
if(b.dataset.model)await modelAction(b.dataset.model);
}));
async function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=(name||'origin0-file').replace(/[\\/:*?"<>|]/g,'_');document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function assetBlob(id){const r=await api('/api/asset?id='+encodeURIComponent(id),undefined,{raw:true});return r.blob()}
async function downloadAsset(id,name){await downloadBlob(await assetBlob(id),name)}
$('export').addEventListener('click',run(async()=>{toast('Preparing runnable branch…');const r=await api('/api/export',undefined,{raw:true});await downloadBlob(await r.blob(),'ORIGIN0_SAVED_BRANCH.zip')}));
$('preferences').addEventListener('submit',run(async e=>{e.preventDefault();await api('/api/settings',{goal:$('goal').value,auto_ui:$('auto-ui').checked,track:$('track').checked,quota_gb:Number($('quota').value)});await api('/api/compute',{target:Number($('compute').value)});if(!$('track').checked)usage.clear();toast('Preferences saved.');await refresh()}));
$('provider-form').addEventListener('submit',run(async e=>{e.preventDefault();provider=await api('/api/provider/connect',{base:$('provider-base').value,key:$('api-key').value,text_model:$('text-model').value,image_model:$('image-model').value,audio_model:$('audio-model').value,enabled:true,remaining:Number($('allowance').value)});$('api-key').value='';providerStatus();toast('Connection configured. Choose an action in Voice & creation.')}));
$('disconnect').addEventListener('click',run(async()=>{provider=await api('/api/provider/connect',{enabled:false});providerStatus();toast('Disconnected. Session key removed.')}));
$('record').addEventListener('click',run(async()=>{if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Voice recording needs a browser with MediaRecorder support. Use a saved audio file instead.');recordStream=await navigator.mediaDevices.getUserMedia({audio:true});const options=MediaRecorder.isTypeSupported('audio/webm')?{mimeType:'audio/webm'}:{};recorder=new MediaRecorder(recordStream,options);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=run(async()=>{clearTimeout(recordTimer);recordStream.getTracks().forEach(x=>x.stop());$('record').textContent='● Record voice';const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});$('voice-preview').src=URL.createObjectURL(blob);$('voice-preview').hidden=false;$('voice-status').textContent='Recording saved locally. Transcription sends it to your configured provider.';await uploadFiles([new File([blob],'voice-'+Date.now()+'.webm',{type:blob.type})]);$('transcribe').disabled=false});recorder.start(1000);$('record').textContent='■ Stop recording';$('voice-status').textContent='Recording now · microphone active';recordTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop()},180000)}));
$('audio-select').addEventListener('change',()=>{latestAudio=$('audio-select').value;$('transcribe').disabled=!latestAudio});$('transcribe').addEventListener('click',run(()=>modelAction('transcribe')));
async function modelAction(kind){const buttons=[...document.querySelectorAll('[data-model],#transcribe')];buttons.forEach(x=>x.disabled=true);$('model-result').textContent='Request running. The local engine continues working.';try{const out=await api('/api/model',{kind,prompt:$('model-prompt').value,asset:kind==='transcribe'?$('audio-select').value:kind==='vision'?$('image-select').value:'',include_source:$('include-source').checked});$('model-result').textContent=out.text||'';if(kind==='image'&&out.asset){const blob=await assetBlob(out.asset.id),img=document.createElement('img');img.alt='Generated image';img.src=URL.createObjectURL(new Blob([blob],{type:'image/png'}));$('model-result').appendChild(img)}if(kind==='transcribe'&&out.text)$('observation').value=out.text;provider=await api('/api/provider');await refresh()}catch(e){$('model-result').textContent=e.message;throw e}finally{buttons.forEach(x=>x.disabled=false);$('transcribe').disabled=!$('audio-select').value}}
$('chatgpt-bridge').addEventListener('click',run(async()=>{const out=await api('/api/bridge',{});await navigator.clipboard.writeText(out.text);toast('Handoff copied. Paste it into your ChatGPT conversation.')}));
$('shutdown').addEventListener('click',run(async()=>{await api('/api/stop',{});toast('State saved. ORIGIN-0 is stopping.')}));
const usage=new Map();let pointerType='mouse',lastMove=0,lastActivity=0;const focusTimes=new WeakMap();
function targetName(el){const node=el.closest?.('[data-panel],button,input,textarea,select');return (node?.id||node?.dataset.panel||node?.dataset.page||node?.dataset.model||node?.tagName?.toLowerCase()||'workspace').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)}
function track(kind,target,ms=0,count=1){if(!state?.lab.track)return;const id=state.ui_genome.id,device=pointerType||'mouse',width=Math.round(innerWidth),key=[kind,target,id,device,Math.floor(width/200)].join(':');const old=usage.get(key)||{kind,target,ui:id,device,width,count:0,total_ms:0,errors:0};old.count+=count;old.total_ms+=ms;usage.set(key,old)}
function active(){const t=performance.now();if(t-lastActivity>3000){lastActivity=t;api('/api/active',{}).catch(()=>{})}}
document.addEventListener('pointerdown',e=>{pointerType=e.pointerType;active();track('pointer-down',targetName(e.target))},{passive:true});document.addEventListener('pointermove',e=>{const t=performance.now();if(t-lastMove>500){lastMove=t;track('pointer-move',targetName(e.target))}},{passive:true});
document.addEventListener('keydown',()=>{pointerType='keyboard';active()},{passive:true});document.addEventListener('input',e=>{if(e.target.type==='password'||e.target.closest('#provider-form'))return;track('input-event',targetName(e.target))},{passive:true});document.addEventListener('focusin',e=>{if(e.target.type!=='password'){focusTimes.set(e.target,performance.now());active()}},{passive:true});document.addEventListener('focusout',e=>{const start=focusTimes.get(e.target);if(start){track('field-dwell',targetName(e.target),Math.min(performance.now()-start,600000));focusTimes.delete(e.target)}},{passive:true});
let lastScroll=0;document.addEventListener('scroll',e=>{const t=performance.now();if(t-lastScroll>400){lastScroll=t;track('scroll',targetName(e.target));active()}},{passive:true,capture:true});let touchStart=null;document.addEventListener('touchstart',e=>{const t=e.touches[0];touchStart=t?{x:t.clientX,y:t.clientY}:null},{passive:true});document.addEventListener('touchend',e=>{const t=e.changedTouches[0];if(touchStart&&t&&Math.hypot(t.clientX-touchStart.x,t.clientY-touchStart.y)>40)track('swipe','workspace');touchStart=null},{passive:true});
setInterval(()=>{if(!usage.size||!state?.lab.track)return;const batch=[...usage.values()].slice(0,100);usage.clear();api('/api/usage',batch).catch(()=>{})},10000);
refresh();api('/api/provider').then(p=>{provider=p;providerStatus()}).catch(()=>{});setInterval(refresh,2000);
