'use strict';
let architecture={schema:'origin0.architecture.v1',name:'My property',rooms:[],views:[]},planURL=null,walkthroughURL=null;
function renderRooms(){$('architecture-rooms').innerHTML=architecture.rooms.map((r,i)=>`<div class="panel" data-room="${i}"><label>Room name<input data-room-key="name" value="${esc(r.name)}" maxlength="80"></label><div class="concept-grid">${[['x','X · m'],['y','Y · m'],['w','Width · m'],['h','Depth · m']].map(([k,l])=>`<label>${l}<input data-room-key="${k}" type="number" min="${k==='w'||k==='h'?'.5':'0'}" max="200" step=".01" value="${esc(r[k])}"></label>`).join('')}</div><label>Door wall<select data-room-key="door">${[['','None'],['top','Top'],['bottom','Bottom'],['left','Left'],['right','Right']].map(([v,l])=>`<option value="${v}" ${r.door===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Door offset · m<input data-room-key="door_offset" type="number" min="0" step=".01" value="${esc(r.door_offset||0)}"></label><label>Door width · m<input data-room-key="door_width" type="number" min=".5" max="2.4" step=".01" value="${esc(r.door_width||.9)}"></label><button data-remove-room="${i}" type="button">Remove room</button></div>`).join('');}
function renderViews(){$('architecture-views').innerHTML=architecture.views.map((v,i)=>`<div class="item" data-view="${i}"><label>View ${i+1}<input data-view-key="label" maxlength="100" value="${esc(v.label)}"></label><label>Room<select data-view-key="room"><option value="">Unassigned</option>${architecture.rooms.map(r=>`<option value="${esc(r.name)}" ${v.room===r.name?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label>Seconds<input data-view-key="seconds" type="number" min="1" max="10" value="${esc(v.seconds)}"></label><div class="actions"><button type="button" data-view-up="${i}" ${i===0?'disabled':''}>Move earlier</button><button type="button" data-view-render="${i}">Render this reference</button><button type="button" data-remove-view="${i}">Remove</button></div></div>`).join('');}
$('architecture-add-room').addEventListener('click',()=>{if(architecture.rooms.length>=30)return toast('The project supports 30 rooms.',true);const last=architecture.rooms.at(-1);architecture.rooms.push({name:'Room '+(architecture.rooms.length+1),x:last?last.x+last.w:0,y:0,w:4,h:3,door:'',door_offset:1,door_width:.9});renderRooms();renderViews()});
$('architecture-rooms').addEventListener('input',e=>{const k=e.target.dataset.roomKey,r=e.target.closest('[data-room]');if(k&&r){const room=architecture.rooms[Number(r.dataset.room)],old=room.name;room[k]=['name','door'].includes(k)?e.target.value:Number(e.target.value);if(k==='name'){for(const v of architecture.views)if(v.room===old)v.room=room.name;renderViews()}}});
$('architecture-rooms').addEventListener('click',e=>{const b=e.target.closest('[data-remove-room]');if(b){const removed=architecture.rooms.splice(Number(b.dataset.removeRoom),1)[0];for(const v of architecture.views)if(v.room===removed.name)v.room='';renderRooms();renderViews()}});
$('architecture-views').addEventListener('input',e=>{const k=e.target.dataset.viewKey,v=e.target.closest('[data-view]');if(k&&v)architecture.views[Number(v.dataset.view)][k]=k==='seconds'?Number(e.target.value):e.target.value});
$('architecture-views').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.removeView!=null){architecture.views.splice(Number(b.dataset.removeView),1);renderViews()}if(b.dataset.viewUp!=null){const i=Number(b.dataset.viewUp);if(i>0)[architecture.views[i-1],architecture.views[i]]=[architecture.views[i],architecture.views[i-1]];renderViews()}if(b.dataset.viewRender!=null){const v=architecture.views[Number(b.dataset.viewRender)];$('native-reference').value=v.asset;$('native-reference-name').textContent=v.label;$('native-strength').value=.25;$('native-strength-value').textContent='.25';$('native-prompt').value=`Architectural photograph of ${v.room?v.room+' · ':''}${v.label}. Preserve the supplied building geometry, openings, proportions and viewpoint. ${$('architecture-light').value}. ${$('architecture-camera').value}. Realistic materials, straight verticals and coherent shadows.`;$('native-shared').checked=false;setPage('images');$('native-prompt').focus();toast('Reference and editable architectural prompt loaded. Review generated geometry.')}});
$('architecture-files').addEventListener('change',run(async e=>{const files=[...e.target.files];if(architecture.views.length+files.length>12)throw new Error('Use up to 12 views');for(const f of files){if(!['image/png','image/jpeg'].includes(f.type)||f.size>64*1024*1024)throw new Error('Use PNG/JPEG files below 64 MiB');const a=await api('/api/upload?name='+encodeURIComponent(f.name),f,{headers:{'Content-Type':f.type}});architecture.views.push({asset:a.id,label:f.name.replace(/\.[^.]+$/,''),seconds:4});renderViews()}e.target.value=''}));
function architectureValues(){architecture.name=$('architecture-name').value;return architecture}
$('architecture-plan').addEventListener('click',run(async()=>{const r=await api('/api/architecture/plan',architectureValues());if(planURL)URL.revokeObjectURL(planURL);planURL=URL.createObjectURL(await assetBlob(r.svg.id));$('architecture-plan-preview').src=planURL;$('architecture-plan-preview').hidden=false;$('architecture-plan-output').innerHTML=`<p>Room area sum: ${r.room_area.toFixed(2)} m²</p><button data-download="${r.svg.id}" data-name="${r.svg.name}">Download SVG plan</button><button data-download="${r.recipe.id}" data-name="${r.recipe.name}">Save project</button>`;}));
$('architecture-walkthrough').addEventListener('click',run(async()=>{$('architecture-walkthrough-status').textContent='Preparing local views…';try{const r=await api('/api/architecture/walkthrough',architectureValues());if(walkthroughURL)URL.revokeObjectURL(walkthroughURL);walkthroughURL=URL.createObjectURL(await assetBlob(r.html.id));$('architecture-walkthrough-preview').src=walkthroughURL;$('architecture-walkthrough-preview').hidden=false;$('architecture-walkthrough-output').innerHTML=`<button data-download="${r.html.id}" data-name="${r.html.name}">Download standalone walkthrough</button><button data-download="${r.recipe.id}" data-name="${r.recipe.name}">Save project</button>`;$('architecture-walkthrough-status').textContent='Ready. Play or export WebM in the preview. The standalone file works offline.'}catch(e){$('architecture-walkthrough-status').textContent=e.message;throw e}}));
$('architecture-import').addEventListener('change',run(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw new Error('Project file is too large');const p=JSON.parse(await f.text());if(p.schema!=='origin0.architecture.v1'||!Array.isArray(p.rooms)||!Array.isArray(p.views)||p.rooms.length>30||p.views.length>12)throw new Error('Unsupported architecture project');architecture=p;$('architecture-name').value=p.name;renderRooms();renderViews();e.target.value=''}));
api('/api/architecture/project',{}).then(p=>{if(p.schema==='origin0.architecture.v1'){architecture=p;$('architecture-name').value=p.name;renderRooms();renderViews()}}).catch(()=>{});

$('architecture-save').addEventListener('click',run(async()=>{const a=await api('/api/architecture/save',architectureValues());await downloadAsset(a.id,a.name);toast('Project saved. Photo references point to this workspace.')}));
window.addArchitectureView=(asset,label)=>{if(architecture.views.length>=12)return toast('This project already has 12 views.',true);architecture.views.push({asset,label:label||'Generated view',seconds:4});renderViews();setPage('production');$('architecture-views').scrollIntoView({block:'center'});toast('Image added to the property project. Save the project to retain it.')};
$('native-jobs').addEventListener('click',e=>{const b=e.target.closest('[data-property-image]');if(b){const j=nativeState?.jobs.find(x=>x.id===b.dataset.propertyImage);if(j?.asset)addArchitectureView(j.asset.id,j.asset.name)}});
