'use strict';
let civic=null,civicBusy=false,civicTab='vision';
const civicRoot=document.createElement('section');civicRoot.id='page-vision';civicRoot.className='page civic';
document.querySelector('main').prepend(civicRoot);
const cvField=(id,label,type='text',value='')=>`<label for="${id}">${label}</label>${type==='textarea'?`<textarea id="${id}" rows="3" maxlength="8000" required>${esc(value)}</textarea>`:`<input id="${id}" type="${type}" value="${esc(value)}" required>`}`;
const cvSelect=(id,label,options)=>`<label for="${id}">${label}</label><select id="${id}">${options.map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join('')}</select>`;
civicRoot.innerHTML=`<div class="section-heading"><div><p class="eyebrow">COMMON VISION / UNDERSTAND · REVIEW · ACT</p><h1>A shared direction, open to revision.</h1><p>Connect needs and disagreements to accountable institutional experiments.</p></div></div>
<div class="civic-status" role="status" id="cv-status">Loading local framework…</div>
<section class="panel"><div class="row spread"><span id="cv-revision"></span><div class="actions"><button id="cv-demo">Load labelled demonstration</button><button id="cv-export">Export recovery JSON</button></div></div><p class="notice">This local prototype does not represent humanity's agreement. Participant identities and coverage are unverified. No publication, spending or institutional action occurs automatically.</p><p id="cv-scope"></p><details><summary>Participation scope and gaps</summary><form id="cv-scope-form">${cvField('cv-scope-input','Scope of participation','textarea')}${cvField('cv-gaps-input','Missing perspectives and uncertainty','textarea')}<button>Save scope</button></form></details></section>
<section class="panel"><div class="civic-tabs" aria-label="Linked framework views">${[['vision','Common vision'],['values','12 + 1 values'],['manifesto','Living manifesto'],['manuscript','Living manuscript'],['programme','Implementation programme']].map(x=>`<button data-cv-tab="${x[0]}">${x[1]}</button>`).join('')}</div><div id="cv-framework"></div></section>
<div class="civic-grid"><section class="panel"><h2>Contribute a perspective</h2><form id="cv-contribution-form"><div class="civic-grid">${cvField('cv-actor','Local actor ID')}${cvSelect('cv-source-type','Source type',[['human','Individual human'],['community','Community record'],['organisation','Organisation'],['expert','Expert submission'],['automated','Automated system']])}${cvSelect('cv-kind','Contribution kind',[['need','Need / experience'],['opinion','Value judgment'],['evidence','Factual claim / evidence'],['objection','Objection'],['solution','Proposed solution']])}${cvSelect('cv-stance','Position',[['neutral','Neutral / undecided'],['support','Support'],['object','Object']])}${cvField('cv-language','Original language','text','en')}${cvField('cv-topic','Topic / need')}</div>${cvField('cv-text','Original contribution','textarea')}${cvField('cv-context','Context / permission provenance','textarea')}<label for="cv-source">Source citation or document reference (required for evidence)</label><input id="cv-source" maxlength="8000"><details><summary>Declared priority and value links</summary><p class="hint">Equal-weight mean of 0–3 judgements. This is not factual confidence or a popularity vote.</p><div class="civic-grid">${['importance','urgency','consequence'].map(x=>cvSelect('cv-'+x,x[0].toUpperCase()+x.slice(1),[['0','0 · unknown / low'],['1','1'],['2','2'],['3','3 · high']])).join('')}</div><div id="cv-contribution-values" class="civic-values-select"></div></details><label class="check"><input id="cv-consent" type="checkbox" required> Permission exists to store and analyse this contribution locally.</label><label class="check"><input id="cv-contribution-demo" type="checkbox"> Demonstration data</label><button class="primary">Save contribution</button></form></section>
<section class="panel"><h2>Needs, objections and coverage</h2><div id="cv-topics"></div><p class="hint">One latest stance per actor ID/topic. Automated, group and demonstration records are shown separately. Repeated posts never become extra human support.</p><div id="cv-contributions"></div></section></div>
<section class="panel"><h2>Institutional proposals</h2><p>Compare both practical reforms and systemic alternatives. Every proposal needs a responsibility, an alternative, and a way to tell whether it helped.</p><details id="cv-proposal-details"><summary>Write a complete proposal</summary><form id="cv-proposal-form"><div class="civic-grid">${[['title','Title'],['topic','Topic'],['need','Need / problem'],['objective','Objective'],['affected','Affected people'],['benefits','Intended benefits (hypotheses)'],['costs','Costs and resources'],['tradeoffs','Trade-offs and burdens'],['alternatives','Alternatives, including status quo'],['owner','Responsible owner'],['authority','Required authority'],['measure','Success measure'],['baseline','Baseline and its evidence'],['target','Target / threshold'],['stop_rule','Stop or revise conditions'],['assumptions','Assumptions and uncertainty']].map(x=>cvField('cv-p-'+x,x[1],['title','topic','owner'].includes(x[0])?'text':'textarea')).join('')}</div><label for="cv-p-contributions">Link contribution IDs (comma separated)</label><input id="cv-p-contributions" required><div id="cv-proposal-values" class="civic-values-select"></div><label class="check"><input id="cv-proposal-demo" type="checkbox"> Demonstration proposal</label><button class="primary">Save proposal for review</button></form></details><div id="cv-proposals"></div></section>
<section class="panel"><h2>Outcome feedback</h2><p>Record observations or simulations against a reviewed, authorised proposal. Reported results are not independently verified.</p><form id="cv-outcome-form"><div class="civic-grid">${cvSelect('cv-o-proposal','Authorised proposal',[])}${cvSelect('cv-o-kind','Evidence category',[['simulation','Simulation / scenario'],['observation','Reported observation']])}${cvField('cv-o-result','Result','textarea')}${cvField('cv-o-measure','Metric, sample and comparison','textarea')}${cvField('cv-o-source','Source / method / date','textarea')}${cvField('cv-o-limitations','Limitations and alternative explanations','textarea')}</div>${cvField('cv-o-next','What should change or be tested next?','textarea')}<label class="check"><input id="cv-outcome-demo" type="checkbox"> Synthetic demonstration outcome</label><button class="primary">Save outcome and update working draft</button></form><div id="cv-outcomes"></div></section>
<section class="panel"><h2>Capability gaps serving the mission</h2><div id="cv-capabilities"></div><p id="cv-limits" class="hint"></p></section>
<section class="panel"><h2>Human decisions and recovery history</h2><p class="hint">The local workspace owner records these decisions. This is not a community vote, verified identity system or external institution's permission.</p><div id="cv-decisions"></div><details><summary>Immutable document snapshots</summary><div id="cv-history"></div></details></section>
<dialog id="cv-review-dialog"><form id="cv-review-form"><h2>Review a specific revision</h2><p id="cv-review-target"></p><input id="cv-review-action" type="hidden"><input id="cv-review-id" type="hidden"><input id="cv-review-revision" type="hidden">${cvField('cv-reviewer','Human reviewer name / local ID')}${cvField('cv-review-reason','Reason, objections considered and authority','textarea')}<label class="check"><input id="cv-review-confirm" type="checkbox" required> I am the human local reviewer and have reviewed this exact revision and its scope.</label><div class="actions"><button class="primary">Record decision</button><button type="button" id="cv-review-close">Cancel</button></div></form></dialog>`;
function civicValues(container){return [...$(container).querySelectorAll('input:checked')].map(x=>x.value)}
function civicDownload(name,bytes,type='application/json'){const u=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function civicAction(action,body={},revision){if(!civic)throw Error('Wait for the workspace to load');await api('/api/vision/action',{action,revision:revision??civic.state.revision,...body});await renderCommonVision(true);toast('Saved locally. Working documents updated.');}
window.renderCommonVision=async function(force=false){if(civicBusy||window.privacyLocked)return;civicBusy=true;try{const next=await api('/api/vision/state',{since:force?0:(civic?.state.revision||0)});if(next.unchanged)return;if(next.load_error){$('cv-status').textContent=next.load_error;return}if(force||!civic||next.state.revision!==civic.state.revision){civic=next;civicRender()}$('cv-status').textContent=next.load_error||'Local workspace ready · drafts update from saved inputs · adopted versions require human review';}catch(e){$('cv-status').textContent=e.message}finally{civicBusy=false}};
function civicFrame(){if(!civic)return;const s=civic.state;const draft=s.frameworks.find(f=>f.id===s.draft),adopted=s.frameworks.find(f=>f.id===s.adopted);let html='';
 if(civicTab==='vision'){html=`<p class="eyebrow">${adopted?'ADOPTED LOCALLY · '+(adopted.demo?'CONTAINS DEMONSTRATION':'UNVERIFIED PARTICIPATION'):'PROVISIONAL · NO ADOPTED VERSION'}</p><blockquote>${esc(adopted?.vision||draft?.vision||'Awaiting a working statement.')}</blockquote><p class="hint">The starter wording is a new prototype draft based on the current brief. It is not the missing original statement.</p><form id="cv-wording-form">${cvField('cv-wording','Proposed common vision','textarea',draft?.vision||'')}<button>Save candidate wording</button></form><p>Working revision ${draft?.revision} · ${draft?.demo?'contains demonstration data':'local contributions only'} · ${esc(draft?.scope)}</p><div class="actions"><button class="primary" data-cv-review="adopt-draft" data-id="${esc(s.draft)}">Review adoption</button><button data-cv-review="reject-draft" data-id="${esc(s.draft)}">Reject candidate</button></div>${adopted?`<details><summary>Adopted snapshot and hash</summary><p>${esc(adopted.id)}</p><code>${esc(adopted.hash)}</code><p>${esc(adopted.scope)}</p></details>`:''}`;}
 else if(civicTab==='values'){html=`<p class="notice">Exact original wording is awaiting source material. The +1 is a distinct principle; its meaning has not been inferred.</p><div class="civic-grid">${s.values.map(v=>`<article class="civic-value ${v.plus_one?'plus-one':''}"><h3>${esc(v.label)}</h3><p>${esc(v.status)}</p><p>${esc(v.original||'Awaiting original source')}</p>${v.meaning?`<p>${esc(v.meaning)}</p>`:''}<small>${esc(v.id)} · source revision ${v.revision}</small></article>`).join('')}</div><details><summary>Supply an original value with human confirmation</summary><form id="cv-value-form">${cvSelect('cv-value-id','Original value slot',s.values.map(v=>[v.id,v.label]))}${cvField('cv-value-text','Exact original wording','textarea')}${cvField('cv-value-source','Source document and location')}<label for="cv-value-meaning">Original explanation (required for +1)</label><textarea id="cv-value-meaning" maxlength="8000"></textarea>${cvField('cv-value-reviewer','Human reviewer')}${cvField('cv-value-reason','Why this is the original source')}<label class="check"><input id="cv-value-confirm" type="checkbox" required> I confirm this source as the local human reviewer.</label><button>Record source and create a new working draft</button></form></details>`;}
 else {const text=draft?.[civicTab]||'';html=`<p class="eyebrow">WORKING ${esc(civicTab)} · REVISION ${draft?.revision} · ${draft?.demo?'DEMONSTRATION INCLUDED':'PROVISIONAL'}</p><p class="hint">All five views derive from snapshot ${esc(draft?.id)}. Adoption preserves the full snapshot.</p><pre class="civic-document">${esc(text)}</pre>${adopted?`<details><summary>Compare adopted ${esc(civicTab)}</summary><pre class="civic-document">${esc(adopted[civicTab])}</pre></details>`:''}`;}
 $('cv-framework').innerHTML=html;document.querySelectorAll('[data-cv-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cvTab===civicTab)));
}
function civicRender(){const s=civic.state;$('cv-revision').textContent=`Knowledge revision ${s.revision} · ${s.adopted?'one locally adopted snapshot':'no adopted snapshot'}`;$('cv-scope').textContent=s.scope+' '+s.gaps;$('cv-scope-input').value=s.scope;$('cv-gaps-input').value=s.gaps;
 for(const id of ['cv-contribution-values','cv-proposal-values']){const checked=civicValues(id);$(id).innerHTML='<p>Value links (pending wording gives no established interpretation)</p>'+s.values.map(v=>`<label class="check"><input type="checkbox" value="${esc(v.id)}" ${checked.includes(v.id)?'checked':''}>${esc(v.label)}</label>`).join('')}
 $('cv-topics').innerHTML=(civic.topics||[]).map(t=>`<article class="item"><h3>${esc(t.topic)}</h3><p>Priority ${t.priority.toFixed(2)}/3 · ${t.human_records} human actor IDs · ${t.support} support / ${t.objections} objections</p><p>${t.automated_records} automated · ${t.organisational_records} group/expert · ${t.demo_records} demonstration IDs</p></article>`).join('')||'<p>No contributions yet. Load the labelled demonstration or submit your first perspective.</p>';
 $('cv-contributions').innerHTML=(s.contributions||[]).slice().reverse().map(c=>`<details class="item" id="${esc(c.id)}"><summary>${c.demo?'DEMO · ':''}${esc(c.kind)} · ${esc(c.actor)} · ${c.withdrawn?'withdrawn':esc(c.stance)}</summary><p>${esc(c.text)}</p><p>${esc(c.source_type)} · ${esc(c.language)} · ${esc(c.topic)}</p><p>${esc(c.source||'No evidence citation')} / ${esc(c.context)}</p><small>${esc(c.id)}</small><p>Values: ${esc((c.values||[]).join(', ')||'awaiting linkage')}</p>${!c.withdrawn?`<button data-cv-review="withdraw" data-id="${esc(c.id)}">Review withdrawal</button>`:''}</details>`).join('');
 $('cv-proposals').innerHTML=(s.proposals||[]).slice().reverse().map(p=>`<article class="item" id="${esc(p.id)}"><p class="eyebrow">${p.demo?'DEMONSTRATION · ':''}${esc(p.status)}</p><h3>${esc(p.title)}</h3><p>${esc(p.objective)}</p><details><summary>Need, alternatives, responsibilities and measures</summary>${[['need','Need'],['affected','Affected'],['benefits','Benefits'],['costs','Costs'],['tradeoffs','Trade-offs'],['alternatives','Alternatives'],['owner','Owner'],['authority','Authority'],['measure','Measure'],['baseline','Baseline'],['target','Target'],['stop_rule','Stop / revise'],['assumptions','Assumptions']].map(x=>`<p><b>${x[1]}:</b> ${esc(p[x[0]])}</p>`).join('')}<p>Contributions: ${esc((p.contributions||[]).join(', '))}</p><p>Value links: ${esc((p.values||[]).join(', ')||'awaiting original framework')}</p></details><small>${esc(p.id)}</small><div class="actions">${p.status==='proposed'?`<button class="primary" data-cv-review="approve-proposal" data-id="${esc(p.id)}">Review proposal</button><button data-cv-review="reject-proposal" data-id="${esc(p.id)}">Reject proposal</button>`:''}${p.status==='reviewed'?`<button data-cv-review="authorise-experiment" data-id="${esc(p.id)}">Record experiment authorisation</button>`:''}${['authorised','measured'].includes(p.status)?`<button data-cv-feedback="${esc(p.id)}">Record feedback</button>`:''}</div></article>`).join('')||'<p>No proposal yet.</p>';
 const selected=$('cv-o-proposal').value;$('cv-o-proposal').innerHTML='<option value="">Select an authorised proposal</option>'+(s.proposals||[]).filter(p=>['authorised','measured'].includes(p.status)).map(p=>`<option value="${esc(p.id)}">${p.demo?'DEMO · ':''}${esc(p.title)}</option>`).join('');$('cv-o-proposal').value=selected;
 $('cv-outcomes').innerHTML=(s.outcomes||[]).slice().reverse().map(o=>`<article class="item"><p class="eyebrow">${o.demo?'DEMONSTRATION · ':''}${esc(o.kind)}</p><p>${esc(o.result)}</p><p>${esc(o.measure)}</p><p>Source: ${esc(o.source)}</p><p>Limits: ${esc(o.limitations)}</p><p>Next: ${esc(o.next)}</p><small>${esc(o.id)} → ${esc(o.proposal)}</small><p><button data-cv-followup="${esc(o.id)}">Draft follow-up proposal</button></p></article>`).join('');
 $('cv-capabilities').innerHTML=civic.capability_gaps.map(g=>`<div class="item"><h3>${esc(g.title)}</h3><p>${esc(g.need)}</p>${g.goal?`<button id="cv-open-development">Prepare technical improvement goal</button>`:''}</div>`).join('');$('cv-limits').textContent=civic.resource_limits;
 $('cv-decisions').innerHTML=(s.decisions||[]).slice().reverse().map(d=>`<details class="item"><summary>${esc(d.action)} · ${esc(d.reviewer)}</summary><p>${esc(d.reason)}</p><p>Revision ${d.revision} · ${esc(d.target)}</p><code>${esc(d.target_hash)}</code></details>`).join('')||'<p>No human decisions recorded.</p>';
 $('cv-history').innerHTML=(s.frameworks||[]).slice().reverse().map(f=>`<div class="item"><b>Revision ${f.revision}${f.id===s.adopted?' · ADOPTED LOCALLY':''}</b><p>${esc(f.vision)}</p><small>${esc(f.id)} · ${esc(f.hash)}</small><button data-cv-snapshot="${esc(f.id)}">Download this snapshot</button></div>`).join('');civicFrame();}
civicRoot.addEventListener('click',run(async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.cvTab){civicTab=b.dataset.cvTab;civicFrame()}
 if(b.id==='cv-demo')await civicAction('demo');if(b.id==='cv-export'){const r=await api('/api/vision/export',{}, {raw:true});civicDownload('ORIGIN0_COMMON_VISION.json',await r.text())}
 if(b.dataset.cvReview){$('cv-review-action').value=b.dataset.cvReview;$('cv-review-id').value=b.dataset.id;$('cv-review-revision').value=civic.state.revision;$('cv-review-target').textContent=`${b.dataset.cvReview} · ${b.dataset.id} · knowledge revision ${civic.state.revision}. Adoption is local only. Experiment authorisation records a decision; this tool does not execute external actions.`;$('cv-review-confirm').checked=false;$('cv-review-reason').value='';$('cv-review-dialog').showModal()}
 if(b.id==='cv-review-close')$('cv-review-dialog').close();
 if(b.dataset.cvFeedback){const p=civic.state.proposals.find(x=>x.id===b.dataset.cvFeedback);$('cv-o-proposal').value=p.id;$('cv-outcome-demo').checked=p.demo;$('cv-o-kind').value='simulation';if(p.demo){$('cv-o-result').value='Synthetic pilot: 6 of 10 submissions received a clear response, compared with an illustrative baseline of 4 of 10.';$('cv-o-measure').value='Demonstration response share: 40% to 60%; no real service was measured.';$('cv-o-source').value='Synthetic fixture for prototype testing; 10 invented records.';$('cv-o-limitations').value='Not causal evidence. No real participants, no privacy audit, no measurement of offline exclusion.';$('cv-o-next').value='Test an offline submission route and workload cap before considering any institutional deployment.'}$('cv-outcome-form').scrollIntoView({behavior:'smooth',block:'start'})}
 if(b.dataset.cvFollowup)await civicAction('follow-up',{id:b.dataset.cvFollowup});
 if(b.dataset.cvSnapshot)civicDownload(b.dataset.cvSnapshot+'.json',JSON.stringify(civic.state.frameworks.find(f=>f.id===b.dataset.cvSnapshot),null,2));
 if(b.id==='cv-open-development'){$('development-goal').value=civic.capability_gaps.find(g=>g.goal).goal;setPage('production');$('development-form').scrollIntoView({block:'start'});toast('Goal prepared. Starting a coding run remains a separate action.');}
}));
civicRoot.addEventListener('submit',run(async e=>{const id=e.target.id;if(!id.startsWith('cv-'))return;e.preventDefault();
 if(id==='cv-contribution-form'){const c={};for(const x of ['actor','kind','stance','language','topic','text','context','source'])c[x]=$('cv-'+x).value;c.source_type=$('cv-source-type').value;for(const x of ['importance','urgency','consequence'])c[x]=Number($('cv-'+x).value);c.consent=$('cv-consent').checked;c.demo=$('cv-contribution-demo').checked;c.values=civicValues('cv-contribution-values');await civicAction('contribute',{contribution:c});$('cv-text').value='';}
 if(id==='cv-scope-form')await civicAction('scope',{text:$('cv-scope-input').value,reason:$('cv-gaps-input').value});
 if(id==='cv-wording-form')await civicAction('amend-vision',{text:$('cv-wording').value});
 if(id==='cv-value-form')await civicAction('value-source',{value:{id:$('cv-value-id').value,original:$('cv-value-text').value,source:$('cv-value-source').value,meaning:$('cv-value-meaning').value},reviewer:$('cv-value-reviewer').value,reason:$('cv-value-reason').value,human:true,confirm:$('cv-value-confirm').checked});
 if(id==='cv-proposal-form'){const p={};for(const x of ['title','topic','need','objective','affected','benefits','costs','tradeoffs','alternatives','owner','authority','measure','baseline','target','stop_rule','assumptions'])p[x]=$('cv-p-'+x).value;p.contributions=$('cv-p-contributions').value.split(',').map(x=>x.trim()).filter(Boolean);p.values=civicValues('cv-proposal-values');p.demo=$('cv-proposal-demo').checked;await civicAction('proposal',{proposal:p})}
 if(id==='cv-outcome-form'){const o={};for(const x of ['proposal','kind','result','measure','source','limitations','next'])o[x]=$('cv-o-'+x).value;o.demo=$('cv-outcome-demo').checked;await civicAction('outcome',{outcome:o})}
 if(id==='cv-review-form'){await civicAction($('cv-review-action').value,{id:$('cv-review-id').value,reviewer:$('cv-reviewer').value,reason:$('cv-review-reason').value,human:true,confirm:$('cv-review-confirm').checked},Number($('cv-review-revision').value));$('cv-review-dialog').close()}
}));
setPage('vision');renderCommonVision();
