'use strict';
let conceptData=null,conceptID='',conceptBusy=false,conceptLast=0,conceptSignature='',conceptPage=0,conceptURLs=[],conceptSearchSig='';
const conceptProject=()=>conceptData?.projects?.find(p=>p.id===conceptID);
function conceptLink(raw){try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
function conceptField(name='',value=''){
 const row=document.createElement('div');row.className='concept-attribute';
 const id='attr-'+crypto.randomUUID();row.innerHTML=`<div><label for="${id}-name">Attribute</label><input id="${id}-name" data-attr-name maxlength="60" placeholder="e.g. colour" value="${esc(name)}"></div><div><label for="${id}-value">Value</label><input id="${id}-value" data-attr-value maxlength="200" placeholder="e.g. blue" value="${esc(value)}"></div><button type="button" data-remove-attr aria-label="Remove attribute">×</button>`;
 $('concept-attrs').append(row);
}
function readConceptAttributes(){return [...$('concept-attrs').children].map(r=>({name:r.querySelector('[data-attr-name]').value.trim(),value:r.querySelector('[data-attr-value]').value.trim()})).filter(x=>x.name&&x.value)}
function liveConceptPrompt(){const attrs=readConceptAttributes();$('concept-prompt-preview').textContent=[$('concept-subject').value.trim(),...attrs.map(a=>a.name+': '+a.value)].filter(Boolean).join(', ')}
function loadConceptForm(){const p=conceptProject();$('concept-name').value=p?.name||'';$('concept-subject').value=p?.subject||'';$('concept-auto').checked=p?.auto_learn??true;$('concept-attrs').replaceChildren();for(const a of p?.attributes||[])conceptField(a.name,a.value);if(!p?.attributes?.length)conceptField();$('concept-query').value=p?.subject||'';conceptSignature='';conceptPage=0;liveConceptPrompt()}
function requireConcept(){if(!conceptID)throw new Error('Save a concept project first.');return conceptID}
async function saveConcept(){const r=await api('/api/concepts/save',{id:conceptID,name:$('concept-name').value,subject:$('concept-subject').value,attributes:readConceptAttributes(),auto_learn:$('concept-auto').checked});conceptID=r.id;await renderConcepts(true);return r}
function clearConceptImages(){for(const u of conceptURLs)URL.revokeObjectURL(u);conceptURLs=[]}
async function conceptPreview(id,el){try{const b=await assetBlob(id);if(!el.isConnected)return;const u=URL.createObjectURL(b);conceptURLs.push(u);el.src=u}catch{el.alt='Preview unavailable. The source file may have moved.'}}
function sourceHTML(s){const link=conceptLink(s.page||s.url);return `<span>${esc(s.license||'unknown licence')} · ${esc(s.creator||'creator not recorded')}</span>${link?` · <a href="${esc(link)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`:''}`}
async function renderConceptExamples(p){
 const filter=$('concept-filter').value,all=(p?.examples||[]).filter(x=>filter==='all'||x.review===filter);const max=Math.max(0,Math.ceil(all.length/12)-1);conceptPage=Math.min(conceptPage,max);const rows=all.slice(conceptPage*12,conceptPage*12+12);
 const signature=JSON.stringify([p?.id,p?.revision,filter,conceptPage]);if(signature===conceptSignature||$('concept-examples').contains(document.activeElement))return;conceptSignature=signature;clearConceptImages();
 $('concept-page-info').textContent=all.length?`${all.length} examples · page ${conceptPage+1}/${max+1}`:'No examples in this view';$('concept-prev').disabled=conceptPage===0;$('concept-next').disabled=conceptPage>=max;
 const root=$('concept-examples');root.replaceChildren();if(!rows.length){root.innerHTML='<div class="concept-empty">Add your own images, search online, or create a logical exercise. Review captions before training.</div>';return}
 for(const x of rows){const card=document.createElement('article');card.className='concept-example';card.dataset.asset=x.asset;const k=x.asset.slice(0,12);card.innerHTML=`<img alt="${esc(x.name)}" loading="lazy"><div class="example-body"><span class="pill">${esc(x.review)} · ${esc(x.split)}</span><h3>${esc(x.name)}</h3><small class="concept-source">${sourceHTML(x.source)}</small><small>${x.width} × ${x.height} · group ${esc(x.group.slice(0,18))}</small><label for="label-${k}">Category you can verify</label><input id="label-${k}" data-example-label maxlength="100" value="${esc(x.label)}" placeholder="e.g. red object"><label for="caption-${k}">What is actually visible?</label><textarea id="caption-${k}" data-example-caption rows="3" maxlength="1000">${esc(x.caption)}</textarea><label for="license-${k}">Source licence / permission</label><select id="license-${k}" data-example-license><option value="unknown">Not recorded</option><option value="cc0">CC0</option><option value="pdm">Public domain</option><option value="by">CC BY · attribution</option><option value="by-sa">CC BY-SA · attribution/share alike</option><option value="owned">I own this image</option><option value="permission">I have permission</option></select><div class="actions"><button class="primary" data-concept-review="accepted">Use for training</button><button data-concept-review="rejected">Exclude</button><button data-concept-review="pending">Pending</button><button data-concept-predict>Predict category</button></div><p data-prediction class="hint"></p></div>`;card.querySelector('[data-example-license]').value=x.source.license||'unknown';root.append(card);conceptPreview(x.asset,card.querySelector('img'))}
}
window.renderConcepts=async function(force=false){
 if(conceptBusy||(!force&&Date.now()-conceptLast<2000))return;conceptBusy=true;conceptLast=Date.now();
 try{conceptData=await api('/api/concepts/state',{});const projects=conceptData.projects||[];
 const select=$('concept-select'),sig=JSON.stringify(projects.map(p=>[p.id,p.name]));if(select.dataset.signature!==sig){select.innerHTML='<option value="">New concept project</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');select.dataset.signature=sig;select.value=conceptID}
 const p=conceptProject();if(conceptID&&!p){conceptID='';loadConceptForm()}
 const rows=p?.examples||[],accepted=rows.filter(x=>x.review==='accepted'),groups=new Set(accepted.map(x=>x.group));$('concept-metrics').innerHTML=`<div><strong>${rows.length}</strong><small>collected</small></div><div><strong>${accepted.length}</strong><small>accepted</small></div><div><strong>${groups.size}</strong><small>example groups</small></div><div><strong>${p?.runs?.length||0}</strong><small>evaluations</small></div>`;
 $('concept-note').textContent=p?.note||'Start with a subject and attributes. Save it, then add examples.';
 const j=conceptData.collection;$('concept-collection-status').textContent=j?.status?`${j.status} · ${j.downloaded||0} downloaded · ${j.message}`:'Online collection is off until you start a search.';$('concept-stop').disabled=!['searching','collecting'].includes(j?.status);
 const jsig=JSON.stringify(j?.results||[]);if(jsig!==conceptSearchSig){conceptSearchSig=jsig;$('concept-search-results').innerHTML=(j?.results||[]).map((x,i)=>`<div class="concept-search-result"><strong>${esc(x.title)}</strong><small class="concept-source"> ${sourceHTML(x.source)}</small><p class="hint">${esc(x.message||'Found in the search index. Review the source before training.')}</p>${!x.asset?`<button data-import-result="${i}">Import this result</button>`:''}</div>`).join('')}
 $('concept-model-note').textContent=p?.active?.id?`Active: ${p.active.method} / ${p.active.metric}. Spatial RGB features; trained only on this project's accepted examples.`:'No project classifier yet. Teach two categories with at least five independent groups each.';
 $('concept-runs').innerHTML=(p?.runs||[]).slice(-5).reverse().map(r=>`<div class="concept-model-result"><b>${r.promoted?'Promoted':'Retained prior model'} · revision ${r.revision}</b><p>Validation: ${(100*r.validation.balanced_accuracy).toFixed(1)}% (${r.validation.total} examples). Audit: ${(100*r.audit.balanced_accuracy).toFixed(1)}% (${r.audit.total} examples).</p><small>${esc(r.reason)}</small></div>`).join('');
 $('concept-training-capability').textContent=conceptData.image_training;await renderConceptExamples(p);
 }catch(e){toast(e.message,true)}finally{conceptBusy=false}
};
$('concept-select').addEventListener('change',run(async e=>{conceptID=e.target.value;loadConceptForm();await renderConcepts(true)}));
$('concept-new').addEventListener('click',()=>{conceptID='';$('concept-select').value='';loadConceptForm();renderConcepts(true);$('concept-name').focus()});
$('concept-form').addEventListener('submit',run(async e=>{e.preventDefault();await saveConcept();toast('Concept saved. Attributes compose a prompt; dataset learning is measured separately.')}));
$('concept-add-attribute').addEventListener('click',()=>{if($('concept-attrs').children.length<20)conceptField()});
$('concept-attrs').addEventListener('click',e=>{if(e.target.closest('[data-remove-attr]')){e.target.closest('.concept-attribute').remove();liveConceptPrompt()}});
$('concept-form').addEventListener('input',liveConceptPrompt);
$('concept-preset').addEventListener('change',e=>{const name=e.target.value;if(!name)return;const presets={horizontal:['horizontal position','left side'],vertical:['vertical position','upper area'],power:['power state','on'],containment:['containment','inside'],colour:['colour','blue'],age:['age','adult, 30 years'],clothing:['clothing','casual clothing'],proportions:['body proportions','natural proportions']};const v=presets[name];conceptField(v[0],v[1]);e.target.value='';liveConceptPrompt()});
for(const axis of ['horizontal','vertical']){$('concept-'+axis).addEventListener('input',e=>{const n=Number(e.target.value);$('concept-'+axis+'-value').textContent=n+'%';const names=axis==='horizontal'?['left side','centre','right side']:['upper area','middle','lower area'];const name=axis+' position',value=names[n<34?0:n>66?2:1]+` (${n}% from the ${axis==='horizontal'?'left':'top'})`;let found=false;for(const row of $('concept-attrs').children){if(row.querySelector('[data-attr-name]').value===name){row.querySelector('[data-attr-value]').value=value;found=true}}if(!found&&$('concept-attrs').children.length<20)conceptField(name,value);liveConceptPrompt()})}
$('concept-use-prompt').addEventListener('click',run(async()=>{const r=await saveConcept();$('native-prompt').value=r.prompt;setPage('images');$('native-prompt').focus();toast('Prompt copied to Image studio. Position wording guides the model; it is not a geometric constraint.')}));
$('concept-search-form').addEventListener('submit',run(async e=>{e.preventDefault();await api('/api/concepts/search',{id:requireConcept(),provider:$('concept-provider').value,query:$('concept-query').value,limit:Number($('concept-search-limit').value),download:$('concept-auto-download').checked});await renderConcepts(true)}));
$('concept-stop').addEventListener('click',run(async()=>{await api('/api/concepts/stop',{});await renderConcepts(true)}));
$('concept-searx-form').addEventListener('submit',run(async e=>{e.preventDefault();await api('/api/concepts/searxng',{url:$('concept-searx-url').value});toast('Search instance configured for this session.')}));
async function uploadConceptFiles(files){requireConcept();const status=$('concept-upload-status');for(let i=0;i<files.length;i++){const f=files[i];status.textContent=`Importing ${i+1}/${files.length}: ${f.name}`;if(f.size>12*1024*1024)throw new Error(f.name+' exceeds 12 MB. Resize it first.');const a=await api('/api/upload?name='+encodeURIComponent(f.name),f,{headers:{'Content-Type':f.type||'application/octet-stream'}});await api('/api/concepts/add',{id:conceptID,asset:a.id,name:f.name,source:{license:$('concept-upload-license').value}})}status.textContent='Images saved. Check each category and caption below.';conceptSignature='';await renderConcepts(true)}
$('concept-files').addEventListener('change',run(async e=>{await uploadConceptFiles([...e.target.files]);e.target.value=''}));
$('concept-drop').addEventListener('drop',run(async e=>{e.preventDefault();e.stopPropagation();document.body.classList.remove('dragover');$('concept-drop').classList.remove('drag-target');await uploadConceptFiles([...e.dataTransfer.files])}));
for(const type of ['dragenter','dragover'])$('concept-drop').addEventListener(type,e=>{e.preventDefault();$('concept-drop').classList.add('drag-target')});$('concept-drop').addEventListener('dragleave',()=>$('concept-drop').classList.remove('drag-target'));
$('concept-search-results').addEventListener('click',e=>{const b=e.target.closest('[data-import-result]');if(!b)return;const r=conceptData.collection.results[Number(b.dataset.importResult)];$('concept-url').value=r.source.url;$('concept-url-page').value=r.source.page;$('concept-url-name').value=r.title;$('concept-url-license').value=r.source.license||'unknown';$('concept-url-import').open=true;$('concept-url-import').scrollIntoView({block:'center',behavior:'smooth'})});
$('concept-url-form').addEventListener('submit',run(async e=>{e.preventDefault();$('concept-url-status').textContent='Downloading and validating image…';await api('/api/concepts/import-url',{id:requireConcept(),name:$('concept-url-name').value,source:{url:$('concept-url').value,page:$('concept-url-page').value,license:$('concept-url-license').value,creator:$('concept-url-creator').value}});$('concept-url-status').textContent='Imported. Review its visible content below.';await renderConcepts(true)}));
$('concept-examples').addEventListener('click',run(async e=>{const b=e.target.closest('button');if(!b)return;const card=b.closest('[data-asset]');if(!card)return;if(b.dataset.conceptReview){b.disabled=true;try{await api('/api/concepts/review',{id:requireConcept(),asset:card.dataset.asset,label:card.querySelector('[data-example-label]').value,caption:card.querySelector('[data-example-caption]').value,review:b.dataset.conceptReview,license:card.querySelector('[data-example-license]').value});document.activeElement?.blur();conceptSignature='';await renderConcepts(true)}finally{b.disabled=false}}if(b.hasAttribute('data-concept-predict')){const out=await api('/api/concepts/predict',{id:requireConcept(),asset:card.dataset.asset});card.querySelector('[data-prediction]').textContent=out.label+'. '+out.note}}));
$('concept-filter').addEventListener('change',()=>{conceptPage=0;renderConcepts(true)});$('concept-prev').addEventListener('click',()=>{conceptPage--;renderConcepts(true)});$('concept-next').addEventListener('click',()=>{conceptPage++;renderConcepts(true)});
$('concept-seed-form').addEventListener('submit',run(async e=>{e.preventDefault();const r=await api('/api/concepts/seed',{id:requireConcept(),axis:$('concept-axis').value});toast(r.examples+' exact synthetic examples added. The classifier was evaluated.');await renderConcepts(true)}));
$('concept-train').addEventListener('click',run(async()=>{await api('/api/concepts/train',{id:requireConcept()});await renderConcepts(true)}));
$('concept-rollback').addEventListener('click',run(async()=>{await api('/api/concepts/rollback',{id:requireConcept()});$('concept-auto').checked=false;await renderConcepts(true)}));
$('concept-train-lora').addEventListener('click',run(async()=>{const p=conceptProject();const j=await api('/api/evolution/start',{kind:'train_lora',concept_id:requireConcept(),prompt:$('concept-prompt-preview').textContent||p.subject,steps:Number($('concept-lora-steps').value),seed:42});evolutionLog=j.id;setPage('learning');await renderEvolution(true);toast('Project adapter job started. Its log and comparison images will appear here.')}));
$('concept-open-runtime').addEventListener('click',()=>setPage('learning'));
for(const [id,images,name] of [['concept-export-recipe',false,'ORIGIN0_CONCEPT_RECIPE.json'],['concept-export-dataset',true,'ORIGIN0_CONCEPT_DATASET.zip']])$(id).addEventListener('click',run(async()=>{const r=await api('/api/concepts/export',{id:requireConcept(),images},{raw:true});await downloadBlob(await r.blob(),name)}));
$('concept-preview-recipe').addEventListener('click',run(async()=>{const r=await api('/api/concepts/preview-contribution',{id:requireConcept()});$('concept-recipe-preview').textContent=r.content;$('concept-recipe-preview').dataset.digest=r.sha256;$('concept-recipe-preview').hidden=false}));

$('concept-publish-form').addEventListener('submit',run(async e=>{e.preventDefault();const digest=$('concept-recipe-preview').dataset.digest;if(!digest)throw new Error('Preview the recipe before publishing.');$('concept-publish-status').textContent='Creating a recipe branch and draft pull request…';try{const r=await api('/api/concepts/publish',{id:requireConcept(),digest,repo:$('concept-fork').value.trim(),token:$('concept-github-token').value});const a=document.createElement('a');a.href=conceptLink(r.url);a.textContent='Open draft contribution ↗';a.target='_blank';a.rel='noopener noreferrer';$('concept-publish-status').replaceChildren(a)}catch(err){$('concept-publish-status').textContent=err.message;throw err}finally{$('concept-github-token').value='';$('concept-reviewed-export').checked=false}}));
