'use strict';
window.privacyLocked=true;
let privacyEnabled=false,privacyLastAction=Date.now();
window.showPrivacy=()=>{window.privacyLocked=true;const frame=document.getElementById('open-studio-frame');if(frame){try{frame.contentWindow.closeMediaChannels?.()}catch{}frame.removeAttribute('src')}document.body.classList.add('privacy-pending');$('privacy-screen').hidden=false;document.title='Private workspace';if(window.stopStudioMedia)window.stopStudioMedia();};
async function syncPrivacy(){try{const p=await api('/api/privacy',{action:'state'});privacyEnabled=p.enabled;window.privacyLocked=p.locked;if(p.locked){showPrivacy();$('privacy-message').textContent=p.problem||'';$('privacy-code').focus()}else{document.body.classList.remove('privacy-pending');$('privacy-screen').hidden=true;document.title='ORIGIN-0 · Local image studio';refreshNative();refresh();if(window.loadHardware)window.loadHardware(false)}}catch(e){showPrivacy();$('privacy-message').textContent=e.message}}
$('lock-workspace').addEventListener('click',run(async()=>{if(!privacyEnabled){setPage('settings');$('privacy-new').focus();toast('Set a PIN and save its recovery code first.');return}await api('/api/privacy',{action:'lock'});showPrivacy();location.reload()}));
$('privacy-unlock').addEventListener('submit',run(async e=>{e.preventDefault();try{await api('/api/privacy',{action:'unlock',pin:$('privacy-code').value});$('privacy-code').value='';location.reload()}catch(err){$('privacy-message').textContent=err.message;$('privacy-code').value=''}}));
$('privacy-recover').addEventListener('click',run(async()=>{try{await api('/api/privacy',{action:'recover',recovery:$('privacy-recovery-input').value});location.reload()}catch(e){$('privacy-message').textContent=e.message}finally{$('privacy-recovery-input').value=''}}));
$('privacy-settings').addEventListener('submit',run(async e=>{e.preventDefault();if($('privacy-new').value!==$('privacy-confirm').value)throw new Error('The two new PINs do not match.');const p=await api('/api/privacy',{action:'set',pin:$('privacy-new').value,current:$('privacy-current').value});for(const id of ['privacy-new','privacy-confirm','privacy-current'])$(id).value='';privacyEnabled=true;await downloadBlob(new Blob(['ORIGIN-0 recovery code\n\n'+p.recovery+'\n\nKeep this code private. It removes the PIN through the recovery form.\n'],{type:'text/plain'}),'ORIGIN0_RECOVERY_CODE.txt');$('privacy-settings-note').textContent='PIN saved. Keep the downloaded recovery code somewhere private.';}));
for(const type of ['pointerdown','keydown','touchstart'])document.addEventListener(type,()=>{privacyLastAction=Date.now()},{passive:true});
setInterval(()=>{if(privacyEnabled&&!window.privacyLocked&&Date.now()-privacyLastAction>600000)$('lock-workspace').click()},15000);
syncPrivacy();
