'use strict';
let finishState=null,finishRefreshBusy=false,finishSignature='',finishImages=new Map();
window.finishOptions=()=>({mode:$('finish-mode').value,long_edge:Number($('finish-size').value),sharpness:Number($('finish-sharpness').value),detail:Number($('finish-detail').value),backend:$('finish-backend').value});
window.useForFinishing=(id,name)=>{$('finish-asset').value=id;$('finish-source-label').textContent=name||'Stored image selected';setPage('production');$('finish-form').scrollIntoView({block:'start',behavior:'smooth'})};
const originalStudioValues=window.studioRequestValues;
window.studioRequestValues=()=>{const r=originalStudioValues();if($('finish-automatic').checked)r.finish=finishOptions();return r};
async function refreshFinishing(){if(finishRefreshBusy||window.privacyLocked)return;finishRefreshBusy=true;try{finishState=await api('/api/finish/state',{});$('finish-availability').textContent=finishState.neural_available?'Real-ESRGAN available · automatic device selection or CPU':'Fast finishing ready · this build has no bundled neural runtime';const jobs=(finishState.jobs||[]).slice().reverse().slice(0,12);const sig=JSON.stringify(jobs.map(j=>[j.id,j.status,j.progress,j.asset?.id]));if(sig!==finishSignature&&!$('finish-history').contains(document.activeElement)){finishSignature=sig;$('finish-history').innerHTML=jobs.map(j=>`<article class="native-job"><div id="finish-preview-${j.id}"></div><div class="native-job-body"><b>${esc(j.status)}${j.cached?' · cached result':''}</b><p>${esc(j.message)}</p><p class="hint">${j.width?j.width+' × '+j.height+' · ':''}${j.seconds?.toFixed(1)||'0'} seconds · ${esc(j.backend||j.request.mode)}</p>${['queued','running'].includes(j.status)?`<progress max="100" value="${j.progress}" aria-label="Finishing progress"></progress><button data-finish-cancel="${j.id}">Cancel</button>`:''}${j.asset?`<div class="actions"><button data-download="${j.asset.id}" data-name="${j.asset.name}">Download PNG</button><button data-download="${j.recipe?.id}" data-name="${j.recipe?.name}">Save recipe</button><button data-finish-original="${j.request.asset}">Compare original</button></div>`:''}${j.log?`<details><summary>Processing log</summary><pre>${esc(j.log)}</pre></details>`:''}</div></article>`).join('')||'<p class="hint">Finished images appear here with their original and processing recipe.</p>';for(const j of jobs){if(j.asset){let u=finishImages.get(j.asset.id);if(!u){u=URL.createObjectURL(new Blob([await assetBlob(j.asset.id)],{type:'image/png'}));finishImages.set(j.asset.id,u)}const img=document.createElement('img');img.src=u;img.alt='Finished image';img.loading='lazy';$('finish-preview-'+j.id)?.replaceChildren(img)}}const visible=new Set(jobs.map(j=>j.asset?.id));for(const[id,u]of finishImages)if(!visible.has(id)){URL.revokeObjectURL(u);finishImages.delete(id)}}}catch(e){$('finish-availability').textContent=e.message}finally{finishRefreshBusy=false}}
$('finish-file').addEventListener('change',run(async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg'].includes(f.type)||f.size>64*1024*1024)throw new Error('Choose a PNG/JPEG below 64 MiB and 60 megapixels');const a=await api('/api/upload?name='+encodeURIComponent(f.name),f,{headers:{'Content-Type':f.type}});$('finish-asset').value=a.id;$('finish-source-label').textContent=f.name;e.target.value=''}));
$('finish-form').addEventListener('submit',run(async e=>{e.preventDefault();if(!$('finish-asset').value)throw new Error('Choose an image or use Finish on a generated result');await api('/api/finish/start',{asset:$('finish-asset').value,...finishOptions()});toast('Finishing queued. The original is preserved.');await refreshFinishing()}));
$('native-jobs').addEventListener('click',e=>{const b=e.target.closest('[data-finish-image]');if(b){const j=nativeState?.jobs.find(x=>x.id===b.dataset.finishImage);if(j?.asset)useForFinishing(j.asset.id,j.asset.name)}});
$('finish-history').addEventListener('click',run(async e=>{const b=e.target.closest('button');if(b?.dataset.finishCancel){await api('/api/finish/cancel',{id:b.dataset.finishCancel});await refreshFinishing()}if(b?.dataset.finishOriginal){const u=URL.createObjectURL(await assetBlob(b.dataset.finishOriginal));const img=$('finish-compare');if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);img.dataset.url=u;img.src=u;img.hidden=false;img.scrollIntoView({behavior:'smooth',block:'center'})}}));
setInterval(refreshFinishing,1800);refreshFinishing();
