'use strict';
let hardwareLoading=false,promptRecorder=null,promptStream=null,promptTimer=null,previewURL=null,previewBusy=false;
window.loadHardware=async apply=>{if(hardwareLoading)return;hardwareLoading=true;try{const r=await api('/api/images/hardware',{profile:$('native-profile').value});$('hardware-summary').textContent=`${r.hardware.cpu} · ${r.hardware.threads} logical CPUs · ${r.hardware.memory_bytes?size(r.hardware.memory_bytes)+' RAM':'RAM not reported'} · ${r.hardware.gpus}`;$('native-recommendation').textContent=r.recommendation.reason;$('native-threads').max=r.hardware.threads;if(apply){$('native-threads').value=r.recommendation.config.threads;$('native-backend').value='auto';$('native-minutes').value=r.recommendation.config.max_minutes;applyImageRecommendation(r.recommendation)}}catch(e){$('hardware-summary').textContent=e.message}finally{hardwareLoading=false}};
function applyImageRecommendation(r){let value=r.width+'x'+r.height;if(![...$('native-size').options].some(x=>x.value===value))$('native-size').add(new Option(`${r.width} × ${r.height}`,value));$('native-size').value=value;$('native-steps').value=r.steps}
$('hardware-defaults').addEventListener('click',()=>loadHardware(true));
$('native-profile').addEventListener('change',run(async()=>{const r=await api('/api/images/hardware',{profile:$('native-profile').value});applyImageRecommendation(r.recommendation);$('native-recommendation').textContent=r.recommendation.reason}));
const promptStyles={natural:'Natural candid photograph, plausible anatomy and proportions, available light, realistic skin or material texture, unforced pose, coherent shadows.',architecture:'Architectural photograph, straight vertical lines, believable scale and room geometry, consistent perspective, realistic materials and natural light.',fashion:'Fashion or product editorial photograph, accurate garment construction and material texture, coherent lighting, carefully framed composition.'};
$('native-structure-prompt').addEventListener('click',()=>{const text=promptStyles[$('native-style').value];if(text){$('native-prompt').value=($('native-prompt').value.trim()+'\n'+text).trim().slice(0,4000);$('native-prompt').focus();toast('Style guidance added. Review it before generating.')}});
window.studioRequestValues=()=>{const [width,height]=$('native-size').value.split('x').map(Number);if($('native-random').checked){const a=new Uint32Array(1);crypto.getRandomValues(a);$('native-seed').value=a[0]&2147483647}return{prompt:$('native-prompt').value,width,height,steps:Number($('native-steps').value),seed:Number($('native-seed').value),shared:$('native-shared').checked,init_asset:$('native-reference').value,strength:Number($('native-strength').value),preview:$('native-preview').checked}};
window.loadStudioRequest=r=>{$('native-rated-defaults').checked=false;$('native-prompt').value=r.prompt;applyImageRecommendation(r);$('native-seed').value=r.seed;$('native-random').checked=false;$('native-reference').value=r.init_asset||'';$('native-reference-name').textContent=r.init_asset?'Stored starting image: '+r.init_asset.slice(0,12):'No starting image selected.';$('native-strength').value=r.strength||.65;$('native-strength-value').textContent=$('native-strength').value;$('native-preview').checked=!!r.preview;};
window.nativeRatingForm=j=>`<details><summary>Your four ratings${j.ratings?' · saved':''}</summary><form data-image-rating="${j.id}">${[['match','Matches the prompt'],['quality','Visual quality'],['consistency','Consistency with intent / reference'],['speed','Speed was acceptable']].map(([id,label])=>`<label>${label}<select name="${id}" required><option value="">Choose…</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${j.ratings?.[id]===n?'selected':''}>${n} · ${['poor','limited','usable','good','excellent'][n-1]}</option>`).join('')}</select></label>`).join('')}<label>What should change?<textarea name="notes" maxlength="1000" rows="2">${esc(j.ratings?.notes||'')}</textarea></label><button type="submit">Save feedback</button><p class="hint">Feedback is saved with this image. It does not silently retrain the model or replace your judgment with an automatic score.</p></form></details>`;
$('native-reference-file').addEventListener('change',run(async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg'].includes(f.type)||f.size>12*1024*1024)throw new Error('Choose a PNG/JPEG below 12 MiB.');const a=await api('/api/upload?name='+encodeURIComponent(f.name),f,{headers:{'Content-Type':f.type}});$('native-reference').value=a.id;$('native-reference-name').textContent=f.name;$('native-shared').checked=false;e.target.value=''}));
$('native-reference-clear').addEventListener('click',()=>{$('native-reference').value='';$('native-reference-name').textContent='No starting image selected.'});
$('native-strength').addEventListener('input',()=>$('native-strength-value').textContent=$('native-strength').value);
$('native-jobs').addEventListener('submit',run(async e=>{const form=e.target.closest('[data-image-rating]');if(!form)return;e.preventDefault();const fd=new FormData(form),ratings={};for(const id of ['match','quality','consistency','speed'])ratings[id]=Number(fd.get(id));ratings.notes=fd.get('notes');await api('/api/images/feedback',{id:form.dataset.imageRating,ratings});toast('Feedback saved with the original settings.');document.activeElement?.blur();nativeJobSignature='';await refreshNative()}));
$('native-jobs').addEventListener('click',run(async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editImage){const j=nativeState.jobs.find(x=>x.id===b.dataset.editImage);if(j?.asset){loadStudioRequest({...j.request,init_asset:j.asset.id,strength:.65});$('native-shared').checked=false;$('native-steps').value=Math.max(8,j.request.steps);$('native-reference-name').textContent='Starting from '+j.id;$('native-prompt').focus();$('native-image-form').scrollIntoView({behavior:'smooth'})}}if(b.dataset.imageMetadata){const r=await api('/api/images/metadata',{id:b.dataset.imageMetadata},{raw:true});await downloadBlob(await r.blob(),'ORIGIN0_IMAGE_SETTINGS.json')}}));
$('native-import-settings').addEventListener('change',run(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw new Error('Settings file is too large');const doc=JSON.parse(await f.text()),r=doc.request;if(doc.schema!=='origin0.image.v1'||typeof r?.prompt!=='string'||r.prompt.length>4000||![r.width,r.height,r.steps,r.seed].every(Number.isFinite)||r.width<256||r.width>1024||r.height<256||r.height>1024)throw new Error('This is not a supported ORIGIN-0 image settings file');loadStudioRequest(r);e.target.value='';toast('Settings loaded. References must exist on this PC. Review before generating.')}));
for(const [id,delta]of [['native-history-prev',-1],['native-history-next',1]])$(id).addEventListener('click',()=>{nativeHistoryPage=Math.max(0,nativeHistoryPage+delta);nativeJobSignature='';refreshNative()});
async function refreshSamplingPreview(){if(previewBusy||window.privacyLocked)return;const j=nativeState?.jobs.find(x=>x.status==='running'&&x.request.preview&&!x.request.shared);if(!j)return;const el=$('preview-'+j.id);if(!el)return;previewBusy=true;try{const r=await fetch('/api/images/preview',{method:'POST',headers:{'X-Origin-Key':key,'Content-Type':'application/json'},body:JSON.stringify({id:j.id})});if(!r.ok)return;const u=URL.createObjectURL(await r.blob());if(previewURL)URL.revokeObjectURL(previewURL);previewURL=u;const im=document.createElement('img');im.src=u;im.alt='Rough intermediate sampling preview';if(el.isConnected)el.replaceChildren(im)}catch{}finally{previewBusy=false}}
setInterval(refreshSamplingPreview,3000);
window.stopStudioMedia=()=>{if(promptRecorder?.state==='recording')promptRecorder.stop();promptStream?.getTracks().forEach(t=>t.stop());};
$('native-dictate').addEventListener('click',run(async()=>{if(promptRecorder?.state==='recording'){promptRecorder.stop();return}const p=await api('/api/provider');if(!p.enabled){setPage('settings');toast('Connect a transcription provider first. It can be a local server.');return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Use a browser with microphone recording support.');promptStream=await navigator.mediaDevices.getUserMedia({audio:true});promptRecorder=new MediaRecorder(promptStream);const chunks=[];promptRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};promptRecorder.onstop=run(async()=>{clearTimeout(promptTimer);promptStream.getTracks().forEach(t=>t.stop());$('native-dictate').textContent='Voice to prompt';if(window.privacyLocked)return;$('native-dictate-status').textContent='Transcribing…';try{const b=new Blob(chunks,{type:promptRecorder.mimeType});const a=await api('/api/upload?name=prompt-voice.webm',b,{headers:{'Content-Type':b.type}});const out=await api('/api/model',{kind:'transcribe',asset:a.id});$('native-prompt').value=($('native-prompt').value+' '+(out.text||'')).trim().slice(0,4000);$('native-dictate-status').textContent='Transcript added. Review your prompt.'}catch(e){$('native-dictate-status').textContent=e.message}});promptRecorder.start(1000);$('native-dictate').textContent='Stop & transcribe';$('native-dictate-status').textContent='Microphone active · up to 2 minutes';promptTimer=setTimeout(()=>promptRecorder.stop(),120000)}));

window.ratedStudioRequest=async()=>{let r=studioRequestValues();if($('native-rated-defaults').checked){const a=await api('/api/images/rated-settings',r);if(a.applied){r=a.request;applyImageRecommendation(r);$('native-rated-note').textContent='Using the best-rated settings from '+a.examples+' comparable local results.'}else $('native-rated-note').textContent='Fewer than three comparable ratings: using the controls above.'}return r};
